//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface BLTBulletinLightsAndSirensReplyInfo : NSObject
{
    _Bool _handledLightsAndSirens;
    _Bool _didPlayLightsAndSirens;
    CDUnknownBlockType _reply;
}

@property(nonatomic) _Bool didPlayLightsAndSirens; // @synthesize didPlayLightsAndSirens=_didPlayLightsAndSirens;
@property(nonatomic) _Bool handledLightsAndSirens; // @synthesize handledLightsAndSirens=_handledLightsAndSirens;
@property(copy, nonatomic) CDUnknownBlockType reply; // @synthesize reply=_reply;
- (void).cxx_destruct;

@end

