//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IDSProtobuf.h"

@class PBCodable;

@interface BLTPBProtobuf : IDSProtobuf
{
    _Bool _hasSequenceNumber;
    _Bool _isInitialSequenceNumber;
    PBCodable *_protobuf;
    unsigned long long _sequenceNumber;
    IDSProtobuf *_idsProtobuf;
}

@property(retain, nonatomic) IDSProtobuf *idsProtobuf; // @synthesize idsProtobuf=_idsProtobuf;
@property(readonly, nonatomic) _Bool isInitialSequenceNumber; // @synthesize isInitialSequenceNumber=_isInitialSequenceNumber;
@property(nonatomic) unsigned long long sequenceNumber; // @synthesize sequenceNumber=_sequenceNumber;
@property(nonatomic) _Bool hasSequenceNumber; // @synthesize hasSequenceNumber=_hasSequenceNumber;
@property(retain, nonatomic) PBCodable *protobuf; // @synthesize protobuf=_protobuf;
- (void).cxx_destruct;
- (id)initWithIDSProtobuf:(id)arg1;
- (id)initWithProtobuf:(id)arg1 type:(unsigned short)arg2 isResponse:(_Bool)arg3 sequenceNumber:(unsigned long long)arg4 isInitialSequenceNumber:(_Bool)arg5;

@end

