//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBCodable.h"

#import "NSCopying.h"

@interface BLTPBTransportData : PBCodable <NSCopying>
{
    unsigned long long _sequenceNumber;
    _Bool _isInitialSequenceNumber;
    struct {
        unsigned int sequenceNumber:1;
        unsigned int isInitialSequenceNumber:1;
    } _has;
}

@property(nonatomic) _Bool isInitialSequenceNumber; // @synthesize isInitialSequenceNumber=_isInitialSequenceNumber;
@property(nonatomic) unsigned long long sequenceNumber; // @synthesize sequenceNumber=_sequenceNumber;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(nonatomic) _Bool hasIsInitialSequenceNumber;
@property(nonatomic) _Bool hasSequenceNumber;

@end

