//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface BLTSectionConfigurationItem : NSObject
{
    _Bool _optOutOfCoordination;
    _Bool _optOutOfAttachmentTransmission;
}

@property(nonatomic) _Bool optOutOfAttachmentTransmission; // @synthesize optOutOfAttachmentTransmission=_optOutOfAttachmentTransmission;
@property(nonatomic) _Bool optOutOfCoordination; // @synthesize optOutOfCoordination=_optOutOfCoordination;
- (id)description;
- (id)initWithDictionary:(id)arg1;

@end

