//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BLTSettingSyncing.h"
#import "MCProfileConnectionObserver.h"

@class BBObserver, BBSettingsGateway, BLTSectionConfiguration, BLTSettingSyncServer, NPSManager, NSString;

@interface BLTSettingSyncInternal : NSObject <MCProfileConnectionObserver, BLTSettingSyncing>
{
    _Bool _dndEnabled;
    _Bool _dndStateUpdatedAtLeastOnce;
    BLTSectionConfiguration *_sectionConfiguration;
    _Bool _isDNDMirrorEnabled;
    _Bool _isWristDetectDisabled;
    BBObserver *_observer;
    BBSettingsGateway *_settingsGateway;
    BLTSettingSyncServer *_connection;
    NPSManager *_npsManager;
}

@property(retain, nonatomic) NPSManager *npsManager; // @synthesize npsManager=_npsManager;
@property(readonly, nonatomic) _Bool isWristDetectDisabled; // @synthesize isWristDetectDisabled=_isWristDetectDisabled;
@property(nonatomic) _Bool isDNDMirrorEnabled; // @synthesize isDNDMirrorEnabled=_isDNDMirrorEnabled;
@property(retain, nonatomic) BLTSettingSyncServer *connection; // @synthesize connection=_connection;
@property(retain, nonatomic) BBSettingsGateway *settingsGateway; // @synthesize settingsGateway=_settingsGateway;
@property(retain, nonatomic) BBObserver *observer; // @synthesize observer=_observer;
- (void).cxx_destruct;
- (unsigned long long)willNanoPresentNotificationForSectionID:(id)arg1 subsectionIDs:(id)arg2;
- (unsigned long long)getSettingsWillPresentBlockedByReasonForSectionInfo:(id)arg1;
- (id)_overriddenSectionInfoForSectionID:(id)arg1;
- (void)setDoNotDisturb:(_Bool)arg1 updateSettings:(_Bool)arg2;
- (void)setSectionSubtypeParametersIcon:(id)arg1 forSectionID:(id)arg2 forSubtypeID:(long long)arg3;
- (void)setSectionInfo:(id)arg1;
- (void)setPrivilegedSenderTypes:(unsigned long long)arg1;
- (void)setBehaviorOverrides:(id)arg1;
- (void)setBehaviorOverrideStatus:(long long)arg1;
- (void)setBehaviorOverrideTypes:(unsigned long long)arg1;
- (void)removeDNDHandlers;
- (void)setDNDHandlers;
- (void)_updateWristDetectSetting;
- (_Bool)_isWristDetectionDisabled;
- (_Bool)_wristDetectionDisabledPreference;
- (_Bool)_wristDetectionEnabledRestriction;
- (void)profileConnectionDidReceiveRestrictionChangedNotification:(id)arg1 userInfo:(id)arg2;
- (void)updateDNDState;
- (void)updateDNDMirrorState;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

