//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BLTSectionInfoListProviderDelegate.h"

@class BLTSectionInfoListBBProvider, BLTSectionInfoListBridgeProvider, NSMutableDictionary, NSString;

@interface BLTSectionInfoList : NSObject <BLTSectionInfoListProviderDelegate>
{
    NSMutableDictionary *_sectionInfoListItemsBySectionID;
    struct _opaque_pthread_mutex_t _lock;
    id <BLTSectionInfoListDelegate> _delegate;
    BLTSectionInfoListBridgeProvider *_overrideProvider;
    BLTSectionInfoListBBProvider *_sectionInfoProvider;
}

@property(retain, nonatomic) BLTSectionInfoListBBProvider *sectionInfoProvider; // @synthesize sectionInfoProvider=_sectionInfoProvider;
@property(retain, nonatomic) BLTSectionInfoListBridgeProvider *overrideProvider; // @synthesize overrideProvider=_overrideProvider;
@property(nonatomic) __weak id <BLTSectionInfoListDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)updateSectionInfo:(id)arg1 withUniversalSectionID:(id)arg2 displayName:(id)arg3;
- (void)updateOverrides:(id)arg1 forSectionID:(id)arg2;
- (id)universalSectionIDForSectionID:(id)arg1;
- (id)effectiveSectionInfoForSectionID:(id)arg1;
- (id)overriddenSectionInfoForSectionID:(id)arg1;
- (id)sectionInfoForSectionID:(id)arg1;
- (void)reloadWithCompletion:(CDUnknownBlockType)arg1;
- (id)effectiveSectionInfos;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

