//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BBObserverDelegate.h"

@class BBObserver, NSObject<OS_dispatch_queue>, NSString;

@interface BLTSectionInfoObserver : NSObject <BBObserverDelegate>
{
    BBObserver *_observer;
    NSObject<OS_dispatch_queue> *_queue;
    CDUnknownBlockType _reloadSectionInfoCompletion;
    id <BLTSectionInfoObserverDelegate> _delegate;
}

@property(nonatomic) __weak id <BLTSectionInfoObserverDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)observer:(id)arg1 updateSectionInfo:(id)arg2;
- (void)_getBBSectionInfoExtendedProperties:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)_reloadSectionInfosWithCompletion:(CDUnknownBlockType)arg1;
- (void)updateSectionInfoBySectionIDs:(id)arg1;
- (void)reloadWithCompletion:(CDUnknownBlockType)arg1;
- (void)_reconnectObserver;
- (void)observer:(id)arg1 noteServerConnectionStateChanged:(_Bool)arg2;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

