//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <BulletinDistributorCompanion/BLTSettingSyncInternal.h>

#import "BBObserverDelegate.h"
#import "BLTSectionInfoListDelegate.h"
#import "PSYSyncCoordinatorDelegate.h"

@class BLTSectionInfoList, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_semaphore>, NSString, PSYSyncCoordinator;

@interface BLTSettingSync : BLTSettingSyncInternal <BBObserverDelegate, PSYSyncCoordinatorDelegate, BLTSectionInfoListDelegate>
{
    PSYSyncCoordinator *_pairedSyncCoordinator;
    NSObject<OS_dispatch_queue> *_sectionInfoSenderQueue;
    NSObject<OS_dispatch_queue> *_sectionInfoProcessingQueue;
    NSObject<OS_dispatch_semaphore> *_sectionInfoSenderReleaseSignal;
    NSObject<OS_dispatch_queue> *_subsectionParameterIconSenderQueue;
    NSObject<OS_dispatch_queue> *_subsectionParameterIconProcessingQueue;
    NSObject<OS_dispatch_semaphore> *_subsectionParameterIconSenderReleaseSignal;
    NSMutableDictionary *_sectionIDsToInfosToSync;
    BLTSectionInfoList *_sectionInfoList;
    _Bool _sendingSectionInfo;
    int _token;
}

- (void).cxx_destruct;
- (void)sectionInfoList:(id)arg1 receivedEffectiveSectionInfo:(id)arg2;
- (void)observer:(id)arg1 noteSectionParametersChanged:(id)arg2 forSectionID:(id)arg3;
- (id)_overriddenSectionInfoForSectionID:(id)arg1;
- (void)_updateAllBBSectionsWithCompletion:(CDUnknownBlockType)arg1 withProgress:(CDUnknownBlockType)arg2;
- (void)_sendSectionSubtypeParameterIcons:(id)arg1 sectionID:(id)arg2 waitForAcknowledgement:(_Bool)arg3 withQueue:(id)arg4 andCompletion:(CDUnknownBlockType)arg5;
- (void)_sendSectionIcon:(id)arg1 forSectionID:(id)arg2 forSubtypeID:(long long)arg3 waitForAcknowledgement:(_Bool)arg4 withQueue:(id)arg5 andCompletion:(CDUnknownBlockType)arg6;
- (void)_sendEffectiveSectionInfo:(id)arg1 waitForAcknowledgement:(_Bool)arg2 withQueue:(id)arg3 andCompletion:(CDUnknownBlockType)arg4;
- (void)_enqueueAndSendEffectiveSectionInfo:(id)arg1;
- (void)_sendEffectiveSectionInfo:(id)arg1;
- (void)removeDNDHandlers;
- (void)setDNDHandlers;
- (void)dealloc;
- (void)syncCoordinatorDidReceiveStartSyncCommand:(id)arg1;
- (id)universalSectionIDForSectionID:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

