//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AFUIDialogPhase, NSArray, NSIndexPath, NSSet, NSString, NSUUID;

@protocol AFUIConversation <NSObject>
- (void)removeItemsWithIdentifiers:(NSSet *)arg1;
- (void)addItemsForAceObjects:(NSArray *)arg1 type:(long long)arg2 dialogPhase:(AFUIDialogPhase *)arg3 asChildrenOfItemWithIdentifier:(NSUUID *)arg4;
- (_Bool)containsItemForAceViewWithIdentifier:(NSString *)arg1;
- (long long)numberOfChildrenForItemAtIndexPath:(NSIndexPath *)arg1;
- (long long)numberOfChildrenForItemWithIdentifier:(NSUUID *)arg1;
- (id <AFUIConversationItem>)parentOfItemWithIdentifier:(NSUUID *)arg1;
- (id <AFUIConversationItem>)lastItem;
- (id <AFUIConversationItem>)itemAtIndexPath:(NSIndexPath *)arg1;
- (id <AFUIConversationItem>)itemWithIdentifier:(NSUUID *)arg1;
- (_Bool)hasItemWithIdentifier:(NSUUID *)arg1;
- (NSIndexPath *)indexPathForItemWithIdentifier:(NSUUID *)arg1;
- (NSUUID *)identifierOfItemAtIndexPath:(NSIndexPath *)arg1;
- (_Bool)containsItemWithIdentifier:(NSUUID *)arg1;
- (id)propertyListRepresentation;
@end

