//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AFUIRequestOptions, AceObject<SAAceCommand>, NSArray, NSBundle, NSIndexPath, NSString, NSURL, NSUUID, SASSpeechRecognized, UIViewController;

@protocol SiriUIPresentationDelegate <NSObject>
- (void)siriPresentation:(id <SiriUIPresentation>)arg1 didShowSnippetWithIdentifier:(NSUUID *)arg2 forInterval:(double)arg3;
- (void)siriPresentation:(id <SiriUIPresentation>)arg1 didScrollForInterval:(double)arg2;
- (void)siriPresentation:(id <SiriUIPresentation>)arg1 didEditSpeechRecognized:(SASSpeechRecognized *)arg2 forInterval:(double)arg3;
- (void)siriPresentationDidDismissBugReporter:(id <SiriUIPresentation>)arg1;
- (void)siriPresentationDidPresentBugReporter:(id <SiriUIPresentation>)arg1;
- (void)siriPresentationPulseHelpButton:(id <SiriUIPresentation>)arg1;
- (void)siriPresentation:(id <SiriUIPresentation>)arg1 setBugReportingAvailable:(_Bool)arg2;
- (void)siriPresentation:(id <SiriUIPresentation>)arg1 setHelpButtonEmphasized:(_Bool)arg2;
- (void)siriPresentation:(id <SiriUIPresentation>)arg1 willDismissViewController:(UIViewController *)arg2;
- (void)siriPresentation:(id <SiriUIPresentation>)arg1 willPresentViewController:(UIViewController *)arg2;
- (void)siriPresentation:(id <SiriUIPresentation>)arg1 setStatusBarHidden:(_Bool)arg2;
- (void)siriPresentation:(id <SiriUIPresentation>)arg1 setStatusViewDisabled:(_Bool)arg2;
- (void)siriPresentation:(id <SiriUIPresentation>)arg1 setStatusViewUserInteractionEnabled:(_Bool)arg2;
- (void)siriPresentation:(id <SiriUIPresentation>)arg1 setCarDisplaySnippetVisible:(_Bool)arg2;
- (void)siriPresentation:(id <SiriUIPresentation>)arg1 setStatusViewHidden:(_Bool)arg2;
- (void)handlePasscodeUnlockForSiriPresentation:(id <SiriUIPresentation>)arg1 withCompletion:(void (^)(long long))arg2;
- (void)siriPresentationRemoveAcousticIDSpinner:(id <SiriUIPresentation>)arg1;
- (void)siriPresentationPresentAcousticIDSpinner:(id <SiriUIPresentation>)arg1;
- (void)getScreenshotImageForSiriPresentation:(id <SiriUIPresentation>)arg1 withCompletion:(void (^)(UIImage *))arg2;
- (void)notifyOnNextUserInteractionForSiriPresentation:(id <SiriUIPresentation>)arg1;
- (void)disableIdleTimerForSiriPresentation:(id <SiriUIPresentation>)arg1;
- (void)enableIdleTimerForSiriPresentation:(id <SiriUIPresentation>)arg1;
- (void)siriPresentation:(id <SiriUIPresentation>)arg1 openURL:(NSURL *)arg2 appBundleID:(NSString *)arg3 allowSiriDismissal:(_Bool)arg4;
- (void)siriPresentation:(id <SiriUIPresentation>)arg1 openURL:(NSURL *)arg2 conversationItemIdentifier:(NSUUID *)arg3 completion:(void (^)(_Bool))arg4;
- (NSBundle *)effectiveCoreLocationBundleForSiriPresentation:(id <SiriUIPresentation>)arg1;
- (void)siriPresentation:(id <SiriUIPresentation>)arg1 performAceCommand:(AceObject<SAAceCommand> *)arg2 conversationItemIdentifier:(NSUUID *)arg3 completion:(void (^)(_Bool))arg4;
- (void)siriPresentation:(id <SiriUIPresentation>)arg1 didCorrectRecognition:(NSString *)arg2 correctionIdentifier:(id)arg3 forItemAtIndexPath:(NSIndexPath *)arg4;
- (void)siriPresentation:(id <SiriUIPresentation>)arg1 didCorrectRecognition:(NSString *)arg2 correctionIdentifier:(id)arg3 forConversationItemWithIdentifier:(NSUUID *)arg4;
- (void)stopSpeakingForSiriPresentation:(id <SiriUIPresentation>)arg1;
- (void)siriPresentation:(id <SiriUIPresentation>)arg1 synthesizeSpeechWithPhoneticText:(NSString *)arg2 completion:(void (^)(void))arg3;
- (void)siriPresentation:(id <SiriUIPresentation>)arg1 synthesizeSpeechWithText:(NSString *)arg2 completion:(void (^)(void))arg3;
- (_Bool)siriIsSpeakingForSiriPresentation:(id <SiriUIPresentation>)arg1;
- (void)siriPresentation:(id <SiriUIPresentation>)arg1 didPresentItemsAtIndexPaths:(NSArray *)arg2;
- (void)siriPresentation:(id <SiriUIPresentation>)arg1 didPresentConversationItemsWithIdentifiers:(NSArray *)arg2;
- (void)siriPresentation:(id <SiriUIPresentation>)arg1 didPrepareAnimationLinkedConversationItem:(NSUUID *)arg2 animationBlock:(void (^)(void))arg3;
- (void)endSiriSessionForSiriPresentation:(id <SiriUIPresentation>)arg1;
- (void)cancelRequestForSiriPresentation:(id <SiriUIPresentation>)arg1;
- (void)stopRecordingSpeechForSiriPresentation:(id <SiriUIPresentation>)arg1;
- (void)siriPresentation:(id <SiriUIPresentation>)arg1 startRequestWithOptions:(AFUIRequestOptions *)arg2;
- (struct CGRect)statusBarFrameForSiriPresentation:(id <SiriUIPresentation>)arg1;
@end

