//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AFUIRequestOptions, NSArray, NSError, NSString, NSURL, NSUUID, UIViewController;

@protocol SiriUIPresentation <NSObject>

@optional
@property(nonatomic) __weak id <SiriUIPresentationDelegate> delegate;
@property(nonatomic) __weak id <SiriUIPresentationDataSource> dataSource;
- (void)presentationStateDidChangeForItemsAtIndexPaths:(NSArray *)arg1;
- (void)removeItemsWithIdentifiers:(NSArray *)arg1 atIndexPaths:(NSArray *)arg2;
- (void)removeItemsWithIdentifiers:(NSArray *)arg1 atIndexPaths:(NSArray *)arg2 parentItemIdentifiers:(NSArray *)arg3;
- (void)reloadItemsAtIndexPaths:(NSArray *)arg1;
- (void)insertItemsAtIndexPaths:(NSArray *)arg1;
- (void)siriRequestWillStart;
- (_Bool)supportsSpeechSynthesis;
- (void)acousticIDRequestDidFinishWithSuccess:(_Bool)arg1;
- (void)siriDidDetectMusic;
- (_Bool)trustsURL:(NSURL *)arg1;
- (void)configureForRequestOptions:(AFUIRequestOptions *)arg1;
- (_Bool)shouldBlockURLOpenOnTTS:(NSURL *)arg1;
- (void)speechRecordingDidFailForRequest:(AFUIRequestOptions *)arg1 onAVRecordRoute:(NSString *)arg2 withError:(NSError *)arg3;
- (void)speechRecordingDidCancelForRequest:(AFUIRequestOptions *)arg1 onAVRecordRoute:(NSString *)arg2;
- (void)speechRecordingDidEndForRequest:(AFUIRequestOptions *)arg1 onAVRecordRoute:(NSString *)arg2;
- (void)siriNetworkAvailabilityDidChange;
- (void)updateSuggestedUtterances:(NSArray *)arg1 forLanguage:(NSString *)arg2;
- (NSArray *)requestContext;
- (void)setScreenSupportsTouchInteraction:(_Bool)arg1;
- (_Bool)shouldDismissForIdling;
- (double)idleTimerInterval;
- (void)didReceiveBugButtonLongPress;
- (void)didReceiveReportBugAction;
- (void)didReceiveHelpAction;
- (AFUIRequestOptions *)siriWillStartRequestWithOptions:(AFUIRequestOptions *)arg1;
- (void)siriAudioRecordingDidChangePowerLevel:(float)arg1;
- (void)siriDidStopSpeaking:(_Bool)arg1;
- (void)siriDidStartSpeaking;
- (void)siriDidHidePasscodeUnlock;
- (void)siriWillHidePasscodeUnlock;
- (void)siriWillShowPasscodeUnlockAndCancelRequest:(_Bool)arg1;
- (void)siriWillShowPasscodeUnlock;
- (void)siriDidTransitionFromState:(long long)arg1 event:(long long)arg2;
- (void)reloadData;
- (void)startNewConversation;
- (void)siriDidFinishActionsForConversationItemWithIdentifier:(NSUUID *)arg1 inConversation:(id <AFUIConversation>)arg2;
- (void)conversation:(id <AFUIConversation>)arg1 didChangePresentationStateForItemsAtIndexPaths:(NSArray *)arg2;
- (void)conversation:(id <AFUIConversation>)arg1 didRemoveItemsWithIdentifiers:(NSArray *)arg2 atIndexPaths:(NSArray *)arg3 parentItemIdentifiers:(NSArray *)arg4;
- (void)conversation:(id <AFUIConversation>)arg1 didUpdateItemsAtIndexPaths:(NSArray *)arg2;
- (void)conversation:(id <AFUIConversation>)arg1 didInsertItemsAtIndexPaths:(NSArray *)arg2;
- (void)statusBarFrameDidChange;
- (void)userInteractionDidOccur;
- (void)siriDidDeactivate;
- (void)siriDidActivateFromSource:(long long)arg1;
- (void)siriWillActivateFromSource:(long long)arg1;
- (UIViewController *)viewController;
- (long long)options;
@end

