//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SiriUIAceObjectViewControllerDelegate.h"

@class NSArray, UIViewController;

@protocol SiriUISnippetViewControllerDelegate <SiriUIAceObjectViewControllerDelegate>
- (void)siriSnippetViewController:(id <SiriUIViewController>)arg1 shouldPresentPicker:(UIViewController *)arg2 completion:(void (^)(_Bool))arg3;
- (void)siriSnippetViewController:(id <SiriUIViewController>)arg1 setStatusBarHidden:(_Bool)arg2;
- (void)siriSnippetViewController:(id <SiriUIViewController>)arg1 setStatusViewHidden:(_Bool)arg2;
- (void)siriSnippetViewControllerViewDidLoad:(id <SiriUIViewController>)arg1;
- (void)siriSnippetViewControllerWillBecomeFirstResponder:(id <SiriUIViewController>)arg1;
- (void)siriSnippetViewController:(id <SiriUIViewController>)arg1 pushSirilandSnippets:(NSArray *)arg2;
@end

