//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SiriUIPresentation.h"

@class NSString;

@interface SiriEyesFreePresentation : NSObject <SiriUIPresentation>
{
    id <SiriUIPresentationDataSource> _dataSource;
    id <SiriUIPresentationDelegate> _delegate;
}

@property(nonatomic) __weak id <SiriUIPresentationDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <SiriUIPresentationDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (_Bool)shouldDismissForIdling;
- (double)idleTimerInterval;
- (void)_didPresentItemsAtIndexPaths:(id)arg1;
- (void)reloadItemsAtIndexPaths:(id)arg1;
- (void)insertItemsAtIndexPaths:(id)arg1;
- (long long)options;
- (void)siriDidDeactivate;
- (void)siriDidActivateFromSource:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

