//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SVSAceCommandRecord : NSObject
{
    id <SAAceCommand> _aceCommand;
    long long _result;
    long long _numberOfStartedActions;
    long long _numberOfSuccessfullyCompletedActions;
    long long _numberOfUnsuccessfullyCompletedActions;
    id <SVSAceCommandRecordDelegate> _delegate;
}

@property(nonatomic) __weak id <SVSAceCommandRecordDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long numberOfUnsuccessfullyCompletedActions; // @synthesize numberOfUnsuccessfullyCompletedActions=_numberOfUnsuccessfullyCompletedActions;
@property(nonatomic) long long numberOfSuccessfullyCompletedActions; // @synthesize numberOfSuccessfullyCompletedActions=_numberOfSuccessfullyCompletedActions;
- (void)_setNumberOfStartedActions:(long long)arg1;
@property(nonatomic) long long numberOfStartedActions; // @synthesize numberOfStartedActions=_numberOfStartedActions;
@property(nonatomic) long long result; // @synthesize result=_result;
@property(readonly, nonatomic) id <SAAceCommand> aceCommand; // @synthesize aceCommand=_aceCommand;
- (void).cxx_destruct;
- (void)incrementNumberOfUnsuccessfullyCompletedActions;
- (void)incrementNumberOfSuccessfullyCompletedActions;
- (void)incrementNumberOfStartedActions;
- (void)_setNumberOfUnsuccessfullyCompletedActions:(long long)arg1;
- (void)_setNumberOfSuccessfullyCompletedActions:(long long)arg1;
- (void)_setResult:(long long)arg1;
- (id)initWithAceCommand:(id)arg1;

@end

