//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AFUIDialogPhase, NSArray, NSIndexSet, NSSet, NSUUID;

@protocol SVSConversationItemList <NSObject>
- (void)removeItemsWithIdentifiers:(NSSet *)arg1;
- (void)removeItemsAtIndexes:(NSIndexSet *)arg1;
- (NSSet *)identifiersForItemsAtIndexes:(NSIndexSet *)arg1;
- (void)addItemsForAceObjects:(NSArray *)arg1 type:(long long)arg2 dialogPhase:(AFUIDialogPhase *)arg3 asChildrenOfItemAtIndex:(long long)arg4;
- (void)addItemsForAceObjects:(NSArray *)arg1 type:(long long)arg2 dialogPhase:(AFUIDialogPhase *)arg3;
- (id <AFUIConversationItem>)itemWithIdentifier:(NSUUID *)arg1;
- (id <AFUIConversationItem>)itemAtIndex:(long long)arg1;
- (long long)numberOfItems;
@end

