//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "AFUIDomainObjectStore.h"
#import "AFUISiriLanguageDelegate.h"
#import "AFUIVoicemailPlayerDelegate.h"
#import "SVSAceCommandRecordsDelegate.h"
#import "SVSConversationDelegate.h"
#import "SVSSiriViewControllerServing.h"
#import "SiriUIPresentationDataSource.h"
#import "SiriUIPresentationDelegate.h"

@class AFManagedStorageConnection, AFUIRequestOptions, AFUISiriLanguage, AFUIVoicemailPlayer, NSMutableArray, NSMutableDictionary, NSMutableSet, NSString, NSTimer, SVSAceCommandRecords, SVSConversationStore, SVSPreferences;

@interface SVSSiriViewController : UIViewController <AFUIDomainObjectStore, AFUIVoicemailPlayerDelegate, SVSAceCommandRecordsDelegate, SVSConversationDelegate, SiriUIPresentationDataSource, SiriUIPresentationDelegate, AFUISiriLanguageDelegate, SVSSiriViewControllerServing>
{
    _Bool _synthesisIsSpeaking;
    unsigned long long _lockState;
    NSMutableSet *_presentedConversationItemRevisionIdentifiers;
    NSMutableDictionary *_synthesisPreparationDictionary;
    NSMutableDictionary *_synthesisAnimationDictionary;
    NSString *_punchoutIdentifierToRegisterAfterUnlock;
    _Bool _supportsSpeechSynthesis;
    _Bool __idleTimerEnabled;
    _Bool _acousticIdAllowed;
    _Bool _waitingForStartRequest;
    _Bool _requestActive;
    id <AFUISiriSession> _session;
    SVSPreferences *_preferences;
    SVSConversationStore *_conversationStore;
    NSMutableArray *_conversations;
    id <SiriUIPresentation> _presentation;
    AFUISiriLanguage *_language;
    id <AFUISpeechSynthesis> _speechSynthesis;
    AFUIVoicemailPlayer *_voicemailPlayer;
    SVSAceCommandRecords *_aceCommandRecords;
    AFUIRequestOptions *_requestOptions;
    NSString *_currentAVRecordRoute;
    unsigned long long _requestStartedCount;
    long long _siriState;
    NSTimer *__idleTimer;
    unsigned long long _wasSiriIdleAndQuiet;
    AFManagedStorageConnection *_domainObjectStorageConnection;
    NSMutableArray *_repeatablePhrases;
    NSString *_utteranceToSpeakAfterClearScreenCommand;
    struct CGRect _statusBarFrame;
}

+ (_Bool)_isSecureForRemoteViewService;
+ (id)_exportedInterface;
+ (id)_remoteViewControllerInterface;
@property(retain, nonatomic, getter=_utteranceToSpeakAfterClearScreenCommand, setter=_setUtteranceToSpeakAfterClearScreenCommand:) NSString *utteranceToSpeakAfterClearScreenCommand; // @synthesize utteranceToSpeakAfterClearScreenCommand=_utteranceToSpeakAfterClearScreenCommand;
@property(retain, nonatomic, getter=_repeatablePhrases, setter=_setRepeatablePhrases:) NSMutableArray *repeatablePhrases; // @synthesize repeatablePhrases=_repeatablePhrases;
@property(nonatomic, getter=_isRequestActive, setter=_setRequestActive:) _Bool requestActive; // @synthesize requestActive=_requestActive;
@property(nonatomic, getter=_isWaitingForStartRequest, setter=_setWaitingForStartRequest:) _Bool waitingForStartRequest; // @synthesize waitingForStartRequest=_waitingForStartRequest;
@property(readonly, nonatomic, getter=_domainObjectStorageConnection) AFManagedStorageConnection *domainObjectStorageConnection; // @synthesize domainObjectStorageConnection=_domainObjectStorageConnection;
@property(nonatomic, getter=_wasSiriIdleAndQuiet, setter=_setWasSiriIdleAndQuiet:) unsigned long long wasSiriIdleAndQuiet; // @synthesize wasSiriIdleAndQuiet=_wasSiriIdleAndQuiet;
@property(nonatomic, getter=_isAcousticIdAllowed, setter=_setAcousticIdAllowed:) _Bool acousticIdAllowed; // @synthesize acousticIdAllowed=_acousticIdAllowed;
@property(nonatomic, getter=_isIdleTimerEnabled, setter=_setIdleTimerEnabled:) _Bool _idleTimerEnabled; // @synthesize _idleTimerEnabled=__idleTimerEnabled;
@property(retain, nonatomic, setter=_setIdleTimer:) NSTimer *_idleTimer; // @synthesize _idleTimer=__idleTimer;
@property(nonatomic, getter=_siriState, setter=_setSiriState:) long long siriState; // @synthesize siriState=_siriState;
@property(nonatomic, getter=_supportsSpeechSynthesis) _Bool supportsSpeechSynthesis; // @synthesize supportsSpeechSynthesis=_supportsSpeechSynthesis;
@property(nonatomic, getter=_requestStartedCount, setter=_setRequestStartedCount:) unsigned long long requestStartedCount; // @synthesize requestStartedCount=_requestStartedCount;
@property(retain, nonatomic, getter=_currentAVRecordRoute, setter=_setCurrentAVRecordRoute:) NSString *currentAVRecordRoute; // @synthesize currentAVRecordRoute=_currentAVRecordRoute;
@property(retain, nonatomic, getter=_requestOptions, setter=_setRequestOptions:) AFUIRequestOptions *requestOptions; // @synthesize requestOptions=_requestOptions;
@property(readonly, nonatomic, getter=_aceCommandRecords) SVSAceCommandRecords *aceCommandRecords; // @synthesize aceCommandRecords=_aceCommandRecords;
@property(retain, nonatomic, getter=_voicemailPlayer, setter=_setVoicemailPlayer:) AFUIVoicemailPlayer *voicemailPlayer; // @synthesize voicemailPlayer=_voicemailPlayer;
@property(readonly, nonatomic, getter=_speechSynthesis) id <AFUISpeechSynthesis> speechSynthesis; // @synthesize speechSynthesis=_speechSynthesis;
@property(readonly, nonatomic, getter=_language) AFUISiriLanguage *language; // @synthesize language=_language;
@property(readonly, nonatomic, getter=_presentation) id <SiriUIPresentation> presentation; // @synthesize presentation=_presentation;
@property(readonly, nonatomic, getter=_conversations) NSMutableArray *conversations; // @synthesize conversations=_conversations;
@property(readonly, nonatomic, getter=_conversationStore) SVSConversationStore *conversationStore; // @synthesize conversationStore=_conversationStore;
@property(nonatomic, getter=_statusBarFrame, setter=_setStatusBarFrame:) struct CGRect statusBarFrame; // @synthesize statusBarFrame=_statusBarFrame;
@property(readonly, nonatomic, getter=_preferences) SVSPreferences *preferences; // @synthesize preferences=_preferences;
@property(retain, nonatomic, getter=_session) id <AFUISiriSession> session; // @synthesize session=_session;
- (void).cxx_destruct;
- (id)_punchoutMetricsAceCommandIdForItemWithIdentifier:(id)arg1;
- (void)_listenAfterSpeakingWithResult:(long long)arg1 recordedRequestCount:(unsigned long long)arg2;
- (void)_addUtterance:(id)arg1;
- (void)_displayNotReadyError;
- (void)_handleRequestError:(id)arg1;
- (_Bool)_isSiriIdleAndQuiet;
- (void)_idleTimerFired:(id)arg1;
- (void)_rescheduleIdleTimerIfNeeded;
- (void)_scheduleIdleTimer;
- (void)_clearIdleTimer;
- (void)_performAppPunchOutCommand:(id)arg1 conversationItemIdentifier:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_performAppPunchOutCommand:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_cancelCurrentTTS:(id)arg1;
- (void)_performGenericAceCommand:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)_dialogPhaseForItemAtIndexPath:(id)arg1;
- (void)_updateLanguageCode;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (id)_presentationViewController;
- (void)_setPresentation:(id)arg1;
- (void)showPresentationWithIdentifier:(id)arg1 properties:(id)arg2;
- (long long)_presentationOptions;
- (void)siriSessionDidFinishAcousticIDRequestWithSuccess:(_Bool)arg1;
- (void)_startRequestWithOptions:(id)arg1;
- (void)setRequestOptions:(id)arg1;
- (void)siriSessionDidFailToStartStarkNotificationRequestWithOptions:(id)arg1;
- (void)siriLanguageSpokenLanguageCodeDidChange:(id)arg1;
- (void)handlePasscodeUnlockForSiriPresentation:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)siriPresentation:(id)arg1 didShowSnippetWithIdentifier:(id)arg2 forInterval:(double)arg3;
- (void)siriPresentation:(id)arg1 didScrollForInterval:(double)arg2;
- (void)siriPresentation:(id)arg1 didEditSpeechRecognized:(id)arg2 forInterval:(double)arg3;
- (void)siriPresentationRemoveAcousticIDSpinner:(id)arg1;
- (void)siriPresentationPresentAcousticIDSpinner:(id)arg1;
- (void)getScreenshotImageForSiriPresentation:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)siriPresentationDidDismissBugReporter:(id)arg1;
- (void)siriPresentationDidPresentBugReporter:(id)arg1;
- (void)siriPresentation:(id)arg1 setBugReportingAvailable:(_Bool)arg2;
- (void)siriPresentationPulseHelpButton:(id)arg1;
- (void)siriPresentation:(id)arg1 setHelpButtonEmphasized:(_Bool)arg2;
- (void)siriPresentation:(id)arg1 setStatusBarHidden:(_Bool)arg2;
- (void)siriPresentation:(id)arg1 willDismissViewController:(id)arg2;
- (void)siriPresentation:(id)arg1 willPresentViewController:(id)arg2;
- (void)siriPresentation:(id)arg1 setStatusViewUserInteractionEnabled:(_Bool)arg2;
- (void)siriPresentation:(id)arg1 setStatusViewDisabled:(_Bool)arg2;
- (void)siriPresentation:(id)arg1 setCarDisplaySnippetVisible:(_Bool)arg2;
- (void)siriPresentation:(id)arg1 setStatusViewHidden:(_Bool)arg2;
- (void)notifyOnNextUserInteractionForSiriPresentation:(id)arg1;
- (void)disableIdleTimerForSiriPresentation:(id)arg1;
- (void)enableIdleTimerForSiriPresentation:(id)arg1;
- (void)siriPresentation:(id)arg1 openURL:(id)arg2 appBundleID:(id)arg3 allowSiriDismissal:(_Bool)arg4;
- (void)siriPresentation:(id)arg1 openURL:(id)arg2 conversationItemIdentifier:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (id)effectiveCoreLocationBundleForSiriPresentation:(id)arg1;
- (void)siriPresentation:(id)arg1 performAceCommand:(id)arg2 conversationItemIdentifier:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)siriPresentation:(id)arg1 didCorrectRecognition:(id)arg2 correctionIdentifier:(id)arg3 forItemAtIndexPath:(id)arg4;
- (void)siriPresentation:(id)arg1 didCorrectRecognition:(id)arg2 correctionIdentifier:(id)arg3 forConversationItemWithIdentifier:(id)arg4;
- (long long)siriPresentation:(id)arg1 presentationStateForItemAtIndexPath:(id)arg2;
- (void)siriPresentation:(id)arg1 synthesizeSpeechWithPhoneticText:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)siriPresentation:(id)arg1 synthesizeSpeechWithText:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)stopSpeakingForSiriPresentation:(id)arg1;
- (_Bool)siriIsSpeakingForSiriPresentation:(id)arg1;
- (void)siriPresentation:(id)arg1 didPresentItemsAtIndexPaths:(id)arg2;
- (void)siriPresentation:(id)arg1 didPresentConversationItemsWithIdentifiers:(id)arg2;
- (void)siriPresentation:(id)arg1 didPrepareAnimationLinkedConversationItem:(id)arg2 animationBlock:(CDUnknownBlockType)arg3;
- (void)_siriPresentation:(id)arg1 speakTextForConversationItemIdentifier:(id)arg2 animationBlock:(CDUnknownBlockType)arg3;
- (void)endSiriSessionForSiriPresentation:(id)arg1;
- (void)cancelRequestForSiriPresentation:(id)arg1;
- (void)stopRecordingSpeechForSiriPresentation:(id)arg1;
- (void)siriPresentation:(id)arg1 startRequestWithOptions:(id)arg2;
- (struct CGRect)statusBarFrameForSiriPresentation:(id)arg1;
- (_Bool)siriPresentation:(id)arg1 itemAtIndexPathIsVirgin:(id)arg2;
- (void)siriPresentation:(id)arg1 setDomainObject:(id)arg2 forIdentifier:(id)arg3;
- (id)siriPresentation:(id)arg1 domainObjectForIdentifier:(id)arg2;
- (id)domainObjectStoreForSiriPresentation:(id)arg1;
- (void)siriPresentation:(id)arg1 addSelectionResponse:(id)arg2;
- (void)siriPresentation:(id)arg1 removeItemsAtIndexPaths:(id)arg2;
- (void)siriPresentation:(id)arg1 insertAceViews:(id)arg2 withDialogPhase:(id)arg3 asItemsAtIndexPaths:(id)arg4;
- (id)siriPresentation:(id)arg1 dialogPhaseForItemAtIndexPath:(id)arg2;
- (id)siriPresentation:(id)arg1 aceCommandIdentifierForItemAtIndexPath:(id)arg2;
- (id)siriPresentation:(id)arg1 aceObjectForItemAtIndexPath:(id)arg2;
- (long long)siriPresentation:(id)arg1 numberOfChildrenForItemAtIndexPath:(id)arg2;
- (long long)siriPresentation:(id)arg1 typeOfItemAtIndexPath:(id)arg2;
- (id)_activeConversationItemAtIndexPath:(id)arg1;
- (id)siriPresentation:(id)arg1 indexPathForItemWithIdentifier:(id)arg2;
- (id)siriPresentation:(id)arg1 identifierOfItemAtIndexPath:(id)arg2;
- (id)startNewConversationForSiriPresentation:(id)arg1;
- (void)siriPresentation:(id)arg1 activateConversationWithIdentifier:(id)arg2;
- (void)siriPresentation:(id)arg1 deleteConversationWithIdentifier:(id)arg2;
- (id)siriPresentation:(id)arg1 conversationWithIdentifier:(id)arg2;
- (id)conversationIdentifiersForSiriPresentation:(id)arg1;
- (long long)siriStateForSiriPresentation:(id)arg1;
- (void)conversation:(id)arg1 presentationStateDidChangeForItemsAtIndexPaths:(id)arg2;
- (void)conversation:(id)arg1 didRemoveItemsWithIdentifiers:(id)arg2 atIndexPaths:(id)arg3 parentItemIdentifiers:(id)arg4;
- (void)conversation:(id)arg1 didUpdateItemsAtIndexPaths:(id)arg2;
- (void)conversation:(id)arg1 didInsertItemsAtIndexPaths:(id)arg2;
- (void)siriSessionDidDetectMusic;
- (_Bool)siriSessionShouldRequestUpdateForViewWithIdentifier:(id)arg1;
- (void)siriSessionSpeechRecordingDidFailWithError:(id)arg1;
- (void)siriSessionSpeechRecordingDidCancel;
- (void)siriSessionSpeechRecordingDidEnd;
- (void)siriSessionSpeechRecordingDidChangeAVRecordRoute:(id)arg1;
- (void)siriSessionDidReceiveSetUIGuidedAccessCommand:(id)arg1;
- (void)siriSessionDidReceiveSetSuggestedUtterancesCommand:(id)arg1;
- (void)siriSessionDidReceiveListenForPronunciationCommand:(id)arg1;
- (void)siriSessionDidReceiveCloseAssistantCommand:(id)arg1;
- (void)siriSessionDidReceiveAppPunchOutCommand:(id)arg1;
- (void)siriSessionDidReceiveUpdateViewsCommand:(id)arg1;
- (void)siriSessionDidReceiveShowHelpCommand:(id)arg1;
- (void)siriSessionDidReceiveRepeatItCommand:(id)arg1;
- (void)siriSessionDidReceiveSayItCommand:(id)arg1;
- (id)_configuredSpeakableUtteranceParserForCommand:(id)arg1 context:(id)arg2 speakableText:(id)arg3 listenAfterSpeaking:(_Bool)arg4 subCompletion:(CDUnknownBlockType)arg5 speakPreparation:(CDUnknownBlockType *)arg6 speakCompletion:(CDUnknownBlockType *)arg7;
- (void)siriSessionDidReceivePlayVoicemailCommand:(id)arg1;
- (void)siriSessionDidReceiveClearScreenCommand:(id)arg1;
- (void)siriSessionDidReceiveAddViewsCommand:(id)arg1;
- (void)siriSessionDidReceiveSpeechPartialResultCommand:(id)arg1;
- (void)siriSessionDidReceiveSpeechRecognizedCommand:(id)arg1;
- (void)siriSessionRequestsDismissal;
- (void)siriSessionOpenURL:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)siriSessionSupportsSpeechSynthesis:(_Bool)arg1;
- (void)siriSessionDidReceiveOpenLinkCommand:(id)arg1;
- (void)siriSessionDidChangeLockState:(unsigned long long)arg1;
- (void)siriSessionDidChangeNetworkAvailability;
- (void)siriSessionGetRequestContextWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)siriSessionDidTransitionFromState:(long long)arg1 toState:(long long)arg2 event:(long long)arg3;
- (void)siriSessionDidFinishRequestWithError:(id)arg1;
- (void)siriSessionAudioRecordingDidChangePowerLevel:(float)arg1;
- (void)siriSessionWillCancelRequest;
- (void)siriSessionWillStartRequest;
- (void)siriSessionWillStartRequestWithOptions:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)siriSessionResultForAceCommand:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)aceCommandRecords:(id)arg1 didChangeResultForCommand:(id)arg2;
- (void)voicemailPlaybackDidFinish:(id)arg1;
- (void)setDomainObject:(id)arg1 forIdentifier:(id)arg2;
- (id)domainObjectForIdentifier:(id)arg1;
- (void)_adjustVoiceTriggerThresholdForTTS:(_Bool)arg1;
- (void)speechSynthesisDidStopSpeakingQueueIsEmpty:(_Bool)arg1;
- (void)speechSynthesisDidStartSpeaking;
- (void)speechSynthesisExecuteAnimationForIdentifier:(id)arg1;
- (void)speechSynthesisGetPreparedTextForIdentifier:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)setSpeechSynthesis:(id)arg1;
- (_Bool)_isSpeechSynthesisSpeaking;
- (void)_cancelSpeechSynthesis;
- (void)_synthesizeText:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_synthesizeProvisionalText:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_synthesizePhoneticText:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_synthesizeSpeechWithText:(id)arg1 isPhonetic:(_Bool)arg2 provisionally:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (void)_didCompleteActionForAceCommand:(id)arg1;
- (void)_speakText:(id)arg1 provisionally:(_Bool)arg2 speakableUtteranceParser:(id)arg3 preparation:(CDUnknownBlockType)arg4 completion:(CDUnknownBlockType)arg5 animationBlock:(CDUnknownBlockType)arg6;
- (id)_aceCommandWithIdentifier:(id)arg1;
- (void)_didStartActionForItemAtIndexPath:(id)arg1 inConversation:(id)arg2;
- (void)_didStartActionForAceCommand:(id)arg1;
- (void)_didReceiveAceCommand:(id)arg1;
- (void)_openURL:(id)arg1 appBundleID:(id)arg2 allowSiriDismissal:(_Bool)arg3;
- (void)_openSensitiveURL:(id)arg1 delaySessionEndForTTS:(_Bool)arg2 conversationItemIdentifier:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)_openSensitiveURL:(id)arg1 delaySessionEndForTTS:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)didReceiveBugButtonLongPress;
- (void)didReceiveReportBugAction;
- (void)didReceiveHelpAction;
- (void)_requestDismissal;
- (void)userInteractionDidOccur;
- (void)siriDidHidePasscodeUnlock;
- (void)siriWillHidePasscodeUnlockForResult:(long long)arg1;
- (void)siriWillShowPasscodeUnlock;
- (void)siriWillShowPasscodeUnlockAndCancelRequest:(_Bool)arg1;
- (void)siriDidDeactivate;
- (void)siriDidActivateFromSource:(long long)arg1;
- (void)siriWillActivateFromSource:(long long)arg1;
- (void)setHostFrontMostAppOrientation:(long long)arg1;
- (id)_presentedConversationItemRevisionIdentifiers;
- (_Bool)_languageMatchesConversation:(id)arg1;
- (id)_previousConversation;
- (id)_startNewConversation;
- (void)_deletePreviousConversation;
- (void)_deleteConversationWithIdentifier:(id)arg1;
- (void)_saveConversation;
- (void)_removePreviousConversationFromStore;
- (void)_activateConversation:(id)arg1;
- (void)_resetContext;
- (id)_conversationWithIdentifier:(id)arg1;
- (id)_activeConversation;
- (void)setStatusBarFrameValue:(id)arg1;
- (id)preferredFocusedItem;
- (void)viewDidMoveToWindow:(id)arg1 shouldAppearOrDisappear:(_Bool)arg2;
- (void)loadView;
- (id)_hostWithErrorHander:(CDUnknownBlockType)arg1;
- (id)_host;
- (void)_cancelLastRootProvisionalSnippetFromLastRequestInConversation:(id)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

