//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SVSStarkCancelButtonGatekeeperHeaderView.h"

@class UIButton, UILabel;

@interface SVSStarkMapsGatekeeperHeaderView : SVSStarkCancelButtonGatekeeperHeaderView
{
    UILabel *_titleLabel;
    UIButton *_keyboardButton;
}

@property(readonly, nonatomic, getter=_keyboardButton) UIButton *keyboardButton; // @synthesize keyboardButton=_keyboardButton;
@property(readonly, nonatomic, getter=_titleLabel) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)_keyboardButtonTapped:(id)arg1;
- (void)_cancelButtonTapped:(id)arg1;
- (void)layoutSubviews;
- (id)initWithRequestOptions:(id)arg1;

@end

