//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSObject<OS_dispatch_queue>, NSString;

@interface SVSSuggestions : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    NSString *_languageCode;
    NSArray *_suggestedUtterances;
    id <SVSSuggestionsDelegate> _delegate;
}

@property(nonatomic) __weak id <SVSSuggestionsDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSArray *suggestedUtterances; // @synthesize suggestedUtterances=_suggestedUtterances;
@property(readonly, nonatomic) NSString *languageCode; // @synthesize languageCode=_languageCode;
- (void).cxx_destruct;
- (void)getSuggestionsWithCompletion:(CDUnknownBlockType)arg1;
- (id)_suggestionsFilePath;
- (id)initWithLanguageCode:(id)arg1 delegate:(id)arg2;

@end

