//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SVSSuggestionsDelegate.h"
#import "SiriUISuggestionsViewDelegate.h"

@class NSString, SVSSuggestions, SiriUISuggestionsView;

@interface SVSSuggestionsViewController : UIViewController <SiriUISuggestionsViewDelegate, SVSSuggestionsDelegate>
{
    SVSSuggestions *_suggestions;
    id <SVSSuggestionsViewControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <SVSSuggestionsViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) SVSSuggestions *suggestions; // @synthesize suggestions=_suggestions;
- (void).cxx_destruct;
- (void)suggestionsDidChange:(id)arg1;
- (void)suggestionsView:(id)arg1 didHideVibrantView:(id)arg2;
- (double)statusViewHeightForSuggestionsView:(id)arg1;
- (double)statusBarHeightForSuggestionsView:(id)arg1;
- (void)didShowSuggestionsForSuggestionsView:(id)arg1;
- (void)getNextSuggestionsForSuggestionsView:(id)arg1 maxSuggestions:(unsigned long long)arg2 completion:(CDUnknownBlockType)arg3;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)animateOut;
- (_Bool)shouldShowBorealisEducation;
- (void)showSuggestions;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)hideAcousticIDSpinner;
- (void)showAcousticIDSpinner;
- (void)_showHeaderText:(id)arg1 subheaderText:(id)arg2 largeSubheaderText:(id)arg3;
- (void)showEmptyView;
- (void)showGreeting;
- (void)showNeedsFirstUnlock;
- (void)showUnavailable;
- (id)_suggestingHeaderText;
- (id)_borealisSubheaderText;
- (id)_borealisHeaderText;
- (id)_initialHeaderText;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) SiriUISuggestionsView *view;

@end

