//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SVSStarkView;

@protocol SVSStarkViewDelegate <NSObject>
- (void)handleSelectButtonTap:(SVSStarkView *)arg1;
- (void)dismissStarkView:(SVSStarkView *)arg1;
@end

