//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "AFUIDebugControllerDelegate.h"
#import "AFUIStateMachineDelegate.h"
#import "RadiosPreferencesDelegate.h"
#import "SVSPagerViewControllerDelegate.h"
#import "SVSSirilandViewDelegate.h"
#import "SVSSuggestionsViewControllerDelegate.h"
#import "SVSTranscriptStackViewControllerDataSource.h"
#import "SVSTranscriptStackViewControllerDelegate.h"
#import "SiriUIPresentation.h"
#import "UIActionSheetDelegate.h"

@class AFUIStateMachine, NSString, RadiosPreferences, SVSPagerViewController, SVSSirilandView, SVSSuggestionsViewController, UIActionSheet;

@interface SVSSirilandViewController : UIViewController <AFUIDebugControllerDelegate, SVSPagerViewControllerDelegate, SVSSirilandViewDelegate, SVSTranscriptStackViewControllerDataSource, SVSSuggestionsViewControllerDelegate, SVSTranscriptStackViewControllerDelegate, UIActionSheetDelegate, RadiosPreferencesDelegate, AFUIStateMachineDelegate, SiriUIPresentation>
{
    _Bool _needsUpdatedUtterances;
    AFUIStateMachine *_stateMachine;
    _Bool _userInteractionDidOccurSinceActivation;
    long long _currentRequestSource;
    id <SiriUIPresentationDataSource> _dataSource;
    id <SiriUIPresentationDelegate> _delegate;
    SVSSuggestionsViewController *_siriUnavailableViewController;
    SVSPagerViewController *_pagerViewController;
    id <AFUIDebugControlling> _debugController;
    double _lastPresentationTime;
    UIActionSheet *_debugActionSheet;
    RadiosPreferences *_radioPreferences;
}

@property(retain, nonatomic) RadiosPreferences *radioPreferences; // @synthesize radioPreferences=_radioPreferences;
@property(retain, nonatomic, getter=_debugActionSheet) UIActionSheet *debugActionSheet; // @synthesize debugActionSheet=_debugActionSheet;
@property(nonatomic) double lastPresentationTime; // @synthesize lastPresentationTime=_lastPresentationTime;
@property(retain, nonatomic) id <AFUIDebugControlling> debugController; // @synthesize debugController=_debugController;
@property(readonly, nonatomic, getter=_pagerViewController) SVSPagerViewController *pagerViewController; // @synthesize pagerViewController=_pagerViewController;
@property(readonly, nonatomic, getter=_siriUnavailableViewController) SVSSuggestionsViewController *siriUnavailableViewController; // @synthesize siriUnavailableViewController=_siriUnavailableViewController;
@property(nonatomic) __weak id <SiriUIPresentationDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <SiriUIPresentationDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (id)_topTranscriptViewController;
- (void)siriNetworkAvailabilityDidChange;
- (void)_updateSiriAvailability:(unsigned long long)arg1 animated:(_Bool)arg2;
- (void)airplaneModeChanged;
- (void)_updateConversationAvailability:(unsigned long long)arg1;
- (void)updateSuggestedUtterances:(id)arg1 forLanguage:(id)arg2;
- (void)_requestUpdatedSuggestionsIfNecessary;
- (id)requestContext;
- (_Bool)shouldDismissForIdling;
- (double)idleTimerInterval;
- (void)_presentRadarComposeController;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)transcriptStackViewController:(id)arg1 didShowSnippetWithIdentifier:(id)arg2 forInterval:(double)arg3;
- (void)transcriptStackViewController:(id)arg1 didScrollForInterval:(double)arg2;
- (void)transcriptStackViewController:(id)arg1 didEditSpeechRecognized:(id)arg2 forInterval:(double)arg3;
- (void)transcriptStackViewController:(id)arg1 shouldPresentPicker:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)transcriptStackViewController:(id)arg1 setStatusBarHidden:(_Bool)arg2;
- (void)transcriptStackViewController:(id)arg1 willDismissViewController:(id)arg2;
- (void)transcriptStackViewController:(id)arg1 willPresentViewController:(id)arg2;
- (void)transcriptStackViewController:(id)arg1 setStatusViewHidden:(_Bool)arg2;
- (_Bool)transcriptStackViewControllerShouldPreventUserInteraction:(id)arg1;
- (void)transcriptStackViewController:(id)arg1 openURL:(id)arg2 conversationItemIdentifier:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (id)effectiveCoreLocationBundleForTranscriptStackViewController:(id)arg1;
- (void)transcriptStackViewController:(id)arg1 synthesizeSpeechWithPhoneticText:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)stopSpeakingForTranscriptStackViewController:(id)arg1;
- (void)transcriptStackViewController:(id)arg1 speakText:(id)arg2 isPhonetic:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (void)cancelRequestForTranscriptStackViewController:(id)arg1;
- (void)transcriptStackViewController:(id)arg1 performAceCommand:(id)arg2 conversationItemIdentifier:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)transcriptStackViewController:(id)arg1 didCorrectRecognition:(id)arg2 correctionIdentifier:(id)arg3 forItemAtIndexPath:(id)arg4;
- (void)transcriptStackViewControllerWillBeginEditing:(id)arg1;
- (void)transcriptStackViewController:(id)arg1 didPresentConversationItemsWithIdentifiers:(id)arg2;
- (void)transcriptStackViewControllerPulseHelpButton:(id)arg1;
- (void)transcriptStackViewController:(id)arg1 setHelpButtonEmphasized:(_Bool)arg2;
- (void)transcriptStackViewController:(id)arg1 didHideVibrantView:(id)arg2;
- (void)transcriptStackViewControllerDidShowSuggestions:(id)arg1;
- (_Bool)transcriptStackViewControllerWillShowSuggestions:(id)arg1;
- (long long)initialDisplayTypeForTranscriptStackViewController:(id)arg1;
- (struct CGRect)statusBarFrameForTranscriptStackViewController:(id)arg1;
- (void)transcriptStackViewControllerDidExitSiriland:(id)arg1;
- (void)transcriptStackViewControllerWillEnterSiriland:(id)arg1;
- (double)statusViewHeightForSuggestionsViewController:(id)arg1;
- (struct CGRect)statusBarFrameForSuggestionsViewController:(id)arg1;
- (void)suggestionsViewDidShowSuggestions:(id)arg1;
- (id)domainObjectStoreForTranscriptStackViewController:(id)arg1;
- (id)conversationForTranscriptStackViewController:(id)arg1;
- (long long)siriStateForTranscriptStackViewController:(id)arg1;
- (void)getScreenshotImageForDebugController:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)debugController:(id)arg1 wantsDismissViewController:(id)arg2;
- (void)debugController:(id)arg1 wantsPresentViewController:(id)arg2;
- (void)debugController:(id)arg1 stateDidChangeWithAddViews:(id)arg2;
- (struct CGRect)statusBarFrameForSirilandView:(id)arg1;
- (void)pagerViewControllerDidChangeTransitionState:(id)arg1;
- (void)pagerViewController:(id)arg1 didActivatePageViewController:(id)arg2 oldActivePageViewController:(id)arg3;
- (void)siriDidDetectMusic;
- (void)_hideAcousticIDSpinner;
- (void)acousticIDRequestDidFinishWithSuccess:(_Bool)arg1;
- (void)speechRecordingDidFailForRequest:(id)arg1 onAVRecordRoute:(id)arg2 withError:(id)arg3;
- (void)speechRecordingDidCancelForRequest:(id)arg1 onAVRecordRoute:(id)arg2;
- (void)speechRecordingDidEndForRequest:(id)arg1 onAVRecordRoute:(id)arg2;
- (_Bool)_shouldEnableIdleTimerForRequestSource:(long long)arg1 andAVRecordRoute:(id)arg2;
- (void)didReceiveBugButtonLongPress;
- (void)didReceiveReportBugAction;
- (void)didReceiveHelpAction;
- (void)siriRequestWillStart;
- (id)siriWillStartRequestWithOptions:(id)arg1;
- (void)siriDidTransitionFromState:(long long)arg1 event:(long long)arg2;
- (void)siriDidHidePasscodeUnlock;
- (void)siriWillHidePasscodeUnlock;
- (void)siriWillShowPasscodeUnlockAndCancelRequest:(_Bool)arg1;
- (void)siriWillShowPasscodeUnlock;
- (void)reloadData;
- (void)startNewConversation;
- (void)siriDidFinishActionsForConversationItemWithIdentifier:(id)arg1 inConversation:(id)arg2;
- (void)conversation:(id)arg1 didChangePresentationStateForItemsAtIndexPaths:(id)arg2;
- (void)conversation:(id)arg1 didRemoveItemsWithIdentifiers:(id)arg2 atIndexPaths:(id)arg3 parentItemIdentifiers:(id)arg4;
- (void)conversation:(id)arg1 didUpdateItemsAtIndexPaths:(id)arg2;
- (void)conversation:(id)arg1 didInsertItemsAtIndexPaths:(id)arg2;
- (void)userInteractionDidOccur;
- (void)siriDidDeactivate;
- (_Bool)_isUsingBuiltInSpeaker;
- (void)siriDidActivateFromSource:(long long)arg1;
- (void)siriWillActivateFromSource:(long long)arg1;
- (void)statusBarFrameDidChange;
- (id)viewController;
- (void)_speakText:(id)arg1;
- (void)_speakText:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_cancelRequest;
- (id)_conversationItemAtIndexPath:(id)arg1 forTranscriptStackViewController:(id)arg2;
- (id)_createTranscriptStackViewController;
- (id)_transcriptStackViewControllerForConversation:(id)arg1;
- (id)_freshTranscriptStackViewController;
- (id)_activeTranscriptStackViewController;
- (id)_previousTranscriptStackViewController;
- (id)_transcriptStackViewControllers;
- (id)_itemInCurrentConversationAtIndexPath:(id)arg1;
- (id)_itemInPreviousConversationAtIndexPath:(id)arg1;
- (id)_activeConversation;
- (id)_previousConversation;
- (id)_identifierOfPreviousConversation;
- (id)_conversationIdentifiers;
- (void)_performTransitionForEvent:(long long)arg1;
- (id)stateMachine:(id)arg1 descriptionForEvent:(long long)arg2;
- (void)stateMachine:(id)arg1 didTransitionFromState:(long long)arg2 forEvent:(long long)arg3;
- (long long)_state;
- (id)_stateMachine;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) SVSSirilandView *view;

@end

