//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class SVSStarkGatekeeperHeaderView, UIButton;

@interface SVSStarkView : UIView
{
    id <SVSStarkViewDelegate> _delegate;
    UIView *_snippetView;
    SVSStarkGatekeeperHeaderView *_gatekeeperHeader;
    UIView *_dismisserView;
    UIButton *_selectButton;
}

@property(retain, nonatomic) UIButton *selectButton; // @synthesize selectButton=_selectButton;
@property(readonly, nonatomic, getter=_dismisserView) UIView *dismisserView; // @synthesize dismisserView=_dismisserView;
@property(retain, nonatomic) SVSStarkGatekeeperHeaderView *gatekeeperHeader; // @synthesize gatekeeperHeader=_gatekeeperHeader;
@property(retain, nonatomic) UIView *snippetView; // @synthesize snippetView=_snippetView;
@property(nonatomic) __weak id <SVSStarkViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)preferredFocusedItem;
- (void)_selectButtonTapped:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

