//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "AFUIQueueDelegate.h"
#import "SVSSuggestionsViewControllerDelegate.h"
#import "SVSTranscriptDataSource.h"
#import "SVSTranscriptDelegate.h"
#import "SiriUIAceObjectViewControllerDelegate.h"
#import "SiriUIAceObjectViewControllerDelegatePrivate.h"
#import "SiriUISnippetViewControllerDelegate.h"
#import "SiriUISnippetViewControllerDelegatePrivate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"

@class NSMutableDictionary, NSMutableSet, NSString, NSUUID, SVSSuggestionsViewController, SVSTranscript, SVSTranscriptAnimationQueue, SVSTranscriptFlowLayout, SVSTranscriptView, SiriUITranscriptItem, UITapGestureRecognizer, UIViewController<SiriUIViewController>;

@interface SVSTranscriptViewController : UIViewController <AFUIQueueDelegate, SiriUISnippetViewControllerDelegate, SiriUISnippetViewControllerDelegatePrivate, SiriUIAceObjectViewControllerDelegate, SiriUIAceObjectViewControllerDelegatePrivate, SVSSuggestionsViewControllerDelegate, SVSTranscriptDataSource, SVSTranscriptDelegate, UICollectionViewDataSource, UICollectionViewDelegate>
{
    long long _updateAnimationCount;
    _Bool _viewIsDisappearing;
    _Bool _viewIsInViewHierarchy;
    _Bool _didLoadConversationList;
    _Bool _showsTranscriptEndWhenVisible;
    id <SVSTranscriptViewControllerDataSource> _dataSource;
    id <SVSTranscriptViewControllerDelegate> _delegate;
    SVSSuggestionsViewController *_suggestionsViewController;
    SVSTranscriptFlowLayout *_layout;
    SVSTranscript *_transcript;
    SVSTranscriptAnimationQueue *_animationQueue;
    SVSTranscriptAnimationQueue *_pinAnimationQueue;
    double _lastAnimationTime;
    double _lastPinAnimationTime;
    double _currentPinMinimumDuration;
    SiriUITranscriptItem *_currentPin;
    NSMutableSet *_identifiersOfItemsWithPendingActions;
    UIViewController<SiriUIViewController> *_editingViewController;
    UITapGestureRecognizer *_editingEndGestureRecognizer;
    double _pinDistance;
    double _gridHeight;
    double _lastTranscriptDragStartTime;
    double _lastTranscriptEditingStartTime;
    NSMutableDictionary *_displayTimeByTranscriptIdentifier;
}

@property(readonly, nonatomic, getter=_displayTimeByTranscriptIdentifier) NSMutableDictionary *displayTimeByTranscriptIdentifier; // @synthesize displayTimeByTranscriptIdentifier=_displayTimeByTranscriptIdentifier;
@property(nonatomic, getter=_lastTranscriptEditingStartTime, setter=_setLastTranscriptEditingStartTime:) double lastTranscriptEditingStartTime; // @synthesize lastTranscriptEditingStartTime=_lastTranscriptEditingStartTime;
@property(nonatomic, getter=_lastTranscriptDragStartTime, setter=_setLastTranscriptDragStartTime:) double lastTranscriptDragStartTime; // @synthesize lastTranscriptDragStartTime=_lastTranscriptDragStartTime;
@property(readonly, nonatomic, getter=_gridHeight) double gridHeight; // @synthesize gridHeight=_gridHeight;
@property(readonly, nonatomic, getter=_pinDistance) double pinDistance; // @synthesize pinDistance=_pinDistance;
@property(nonatomic, getter=_showsTranscriptEndWhenVisible, setter=_setShowsTranscriptEndWhenVisible:) _Bool showsTranscriptEndWhenVisible; // @synthesize showsTranscriptEndWhenVisible=_showsTranscriptEndWhenVisible;
@property(retain, nonatomic, getter=_editingEndGestureRecognizer, setter=_setEditingEndGestureRecognizer:) UITapGestureRecognizer *editingEndGestureRecognizer; // @synthesize editingEndGestureRecognizer=_editingEndGestureRecognizer;
@property(retain, nonatomic, getter=_editingViewController, setter=_setEditingViewController:) UIViewController<SiriUIViewController> *editingViewController; // @synthesize editingViewController=_editingViewController;
@property(readonly, nonatomic, getter=_identifiersOfItemsWithPendingActions) NSMutableSet *identifiersOfItemsWithPendingActions; // @synthesize identifiersOfItemsWithPendingActions=_identifiersOfItemsWithPendingActions;
@property(retain, nonatomic, getter=_currentPin, setter=_setCurrentPin:) SiriUITranscriptItem *currentPin; // @synthesize currentPin=_currentPin;
@property(nonatomic, getter=_currentPinMinimumDuration, setter=_setCurrentPinMinimumDuration:) double currentPinMinimumDuration; // @synthesize currentPinMinimumDuration=_currentPinMinimumDuration;
@property(nonatomic, getter=_lastPinAnimationTime, setter=_setLastPinAnimationTime:) double lastPinAnimationTime; // @synthesize lastPinAnimationTime=_lastPinAnimationTime;
@property(nonatomic, getter=_lastAnimationTime, setter=_setLastAnimationTime:) double lastAnimationTime; // @synthesize lastAnimationTime=_lastAnimationTime;
@property(readonly, nonatomic, getter=_pinAnimationQueue) SVSTranscriptAnimationQueue *pinAnimationQueue; // @synthesize pinAnimationQueue=_pinAnimationQueue;
@property(readonly, nonatomic, getter=_animationQueue) SVSTranscriptAnimationQueue *animationQueue; // @synthesize animationQueue=_animationQueue;
@property(nonatomic, getter=_didLoadConversationList, setter=_setDidLoadConversationList:) _Bool didLoadConversationList; // @synthesize didLoadConversationList=_didLoadConversationList;
@property(readonly, nonatomic, getter=_transcript) SVSTranscript *transcript; // @synthesize transcript=_transcript;
@property(readonly, nonatomic, getter=_layout) SVSTranscriptFlowLayout *layout; // @synthesize layout=_layout;
@property(readonly, nonatomic, getter=_suggestionsViewController) SVSSuggestionsViewController *suggestionsViewController; // @synthesize suggestionsViewController=_suggestionsViewController;
@property(nonatomic, getter=_viewIsInViewHierarchy, setter=_setViewIsInViewHierarchy:) _Bool viewIsInViewHierarchy; // @synthesize viewIsInViewHierarchy=_viewIsInViewHierarchy;
@property(nonatomic) __weak id <SVSTranscriptViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <SVSTranscriptViewControllerDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (void)_logMetricsForSnippetAtIndexPath:(id)arg1;
- (void)_logMetricsForVisibleSnippets;
- (void)siriStoppedFingerprintingMusic;
- (void)siriBeganFingerprintingMusic;
- (void)_animateSnippetConfirmation:(id)arg1;
- (void)_animateSnippetCancellation:(id)arg1;
- (id)_tossAnimationForCell;
- (void)_animateSnippetTossInCell:(id)arg1;
- (void)_performNextAnimation;
- (_Bool)_shouldConditionallyPinToTranscriptItem:(id)arg1;
- (void)_performNextPinAnimation;
- (void)_processPinAnimationQueue;
- (void)_scheduleNextPinAnimationAfterDelay:(double)arg1;
- (void)_processAnimationQueue;
- (void)_scheduleNextAnimationAfterDelay:(double)arg1;
- (double)_nextPinAnimationTime;
- (double)_nextAnimationTime;
- (void)queue:(id)arg1 didEnqueueObjects:(id)arg2;
- (void)animateTranscriptWithUpdates:(CDUnknownBlockType)arg1;
- (double)_pinDistanceFromTop;
- (struct UIEdgeInsets)_requiredExtraSpaceToPinTranscriptItem:(id)arg1;
- (void)_appendExtraSpaceToContentInsets;
- (void)_pinTranscriptToCurrentPin;
- (struct CGRect)_frameForItemAtIndex:(unsigned long long)arg1;
- (void)pinItemWithIdentifier:(id)arg1;
- (void)_tappedOutsideEditingView:(id)arg1;
- (void)_teardownEditingViewController:(id)arg1;
- (void)_setupEditingForViewController:(id)arg1;
- (id)_indexPathForFirstResponder;
- (void)_keyboardWillHide:(id)arg1;
- (void)_keyboardDidShow:(id)arg1;
- (id)_indexPathForItemAtIndex:(long long)arg1;
- (id)_indexPathsForItemsAtIndexes:(id)arg1;
- (id)_transcriptItemForSiriViewController:(id)arg1;
- (void)_registerReusableView:(Class)arg1;
- (id)_aceViewControllerIfExistsAtItemIndex:(long long)arg1;
- (id)_snippetViewControllerIfExistsAtItemIndex:(long long)arg1;
- (id)_snippetViewControllerIfExistsForTranscriptItem:(id)arg1;
- (id)_aceViewControllerIfExistsForTranscriptItem:(id)arg1;
- (id)_controllerForItemIndex:(long long)arg1;
- (Class)aceControllerCellClass;
- (Class)snippetControllerCellClass;
- (double)_expectedWidthForItemIndex:(unsigned long long)arg1;
- (_Bool)_itemIndexIsInset:(unsigned long long)arg1;
- (struct UIEdgeInsets)_edgeInsetsForItemIndex:(unsigned long long)arg1;
- (void)_updateBottomKeylineForScrollView:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (double)_heightForFooterAtItemIndex:(long long)arg1;
- (double)_heightForHeaderAtItemIndex:(long long)arg1;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)transcript:(id)arg1 performAceCommands:(id)arg2 conversationItemIdentifier:(id)arg3;
- (void)transcript:(id)arg1 presentationStateDidChangeForItemsAtIndexPaths:(id)arg2;
- (void)transcript:(id)arg1 didRemoveTranscriptItems:(id)arg2 atIndexes:(id)arg3;
- (void)transcript:(id)arg1 didReloadTranscriptItemsAtIndexes:(id)arg2;
- (void)transcript:(id)arg1 didReplaceTranscriptItemsAtIndexes:(id)arg2 replacedTranscriptItems:(id)arg3;
- (id)_invalidIndexesToRemoveBeforeIndex:(long long)arg1;
- (void)transcript:(id)arg1 didDiscardTranscriptItemsWithConversationItemIdentifiers:(id)arg2;
- (void)transcript:(id)arg1 didInsertTranscriptItemsAtIndexes:(id)arg2;
- (void)_removeConversationItemWithIdentifier:(id)arg1;
- (void)_removeConversationItemsWithIdentifiers:(id)arg1;
- (void)_updateTitle;
- (id)viewControllerDelegateForTranscript:(id)arg1;
- (long long)transcript:(id)arg1 presentationStateForItemAtIndex:(long long)arg2;
- (id)transcript:(id)arg1 aceObjectForItemAtIndex:(long long)arg2;
- (_Bool)transcript:(id)arg1 itemAtIndexIsVirgin:(long long)arg2;
- (id)transcript:(id)arg1 aceCommandIdentifierForItemAtIndex:(long long)arg2;
- (id)transcript:(id)arg1 dialogPhaseForItemAtIndex:(long long)arg2;
- (id)transcript:(id)arg1 identifierOfItemAtIndex:(long long)arg2;
- (id)_aceCommandIdentifierForItemAtIndex:(long long)arg1;
- (id)_dialogPhaseForItemAtIndex:(long long)arg1;
- (id)_conversationItemAtIndex:(long long)arg1;
- (long long)numberOfItemsInTranscript:(id)arg1;
- (double)statusViewHeightForSuggestionsViewController:(id)arg1;
- (struct CGRect)statusBarFrameForSuggestionsViewController:(id)arg1;
- (void)suggestionsViewController:(id)arg1 didHideVibrantView:(id)arg2;
- (void)suggestionsViewDidShowSuggestions:(id)arg1;
- (void)cancelSpeakingForSiriViewController:(id)arg1;
- (void)siriViewController:(id)arg1 speakText:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_speakText:(id)arg1 isPhonetic:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)siriSnippetViewController:(id)arg1 shouldPresentPicker:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)siriSnippetViewController:(id)arg1 setStatusBarHidden:(_Bool)arg2;
- (void)siriSnippetViewController:(id)arg1 willDismissViewController:(id)arg2;
- (void)siriSnippetViewController:(id)arg1 willPresentViewController:(id)arg2;
- (void)siriSnippetViewController:(id)arg1 setStatusViewHidden:(_Bool)arg2;
- (void)siriViewController:(id)arg1 didHideVibrantView:(id)arg2;
- (id)persistentStoreForSiriViewController:(id)arg1;
- (void)cancelRequestForSiriSnippetViewController:(id)arg1;
- (void)siriSnippetViewControllerViewDidLoad:(id)arg1;
- (void)siriSnippetViewControllerWillBecomeFirstResponder:(id)arg1;
- (double)siriSnippetViewControllerExpectedWidth:(id)arg1;
- (void)siriViewController:(id)arg1 setContentOffset:(double)arg2;
- (struct UIEdgeInsets)siriViewControllerDisplayInsetsForVisibleSpace:(id)arg1;
- (struct CGSize)siriViewControllerVisibleContentArea:(id)arg1;
- (double)siriViewControllerExpectedWidth:(id)arg1;
- (void)siriViewControllerHeightDidChange:(id)arg1 pinTopOfSnippet:(_Bool)arg2;
- (void)siriViewControllerHeightDidChange:(id)arg1;
- (void)siriSnippetViewController:(id)arg1 pushSirilandSnippets:(id)arg2;
- (void)removeSiriViewController:(id)arg1;
- (void)siriViewController:(id)arg1 startCorrectedSpeechRequestWithText:(id)arg2 correctionIdentifier:(id)arg3;
- (void)siriViewControllerDidEndEditing:(id)arg1;
- (void)siriViewControllerWillBeginEditing:(id)arg1;
- (_Bool)siriViewControllerShouldPreventUserInteraction:(id)arg1;
- (void)siriViewController:(id)arg1 addSelectionResponse:(id)arg2;
- (id)siriViewController:(id)arg1 listItemToPickInAutodisambiguationForListItems:(id)arg2;
- (id)siriViewController:(id)arg1 disambiguationItemForListItem:(id)arg2 disambiguationKey:(id)arg3;
- (id)siriViewControllerEffectiveBundleForCoreLocation:(id)arg1;
- (_Bool)siriViewController:(id)arg1 openPunchOut:(id)arg2;
- (void)siriViewController:(id)arg1 setDomainObject:(id)arg2 forIdentifier:(id)arg3;
- (id)siriViewController:(id)arg1 domainObjectForIdentifier:(id)arg2;
- (id)_domainObjectStore;
- (void)siriViewController:(id)arg1 sendGenericAceCommands:(id)arg2;
- (void)siriViewController:(id)arg1 openURL:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (_Bool)siriViewController:(id)arg1 openURL:(id)arg2;
- (void)siriViewController:(id)arg1 performAceCommands:(id)arg2;
- (id)requestContext;
- (void)siriRequestWillStart;
- (void)siriDidFinishActionsForConversationItemWithIdentifier:(id)arg1;
- (void)presentationStateDidChangeForItemsAtIndexes:(id)arg1;
- (void)removeItemsWithIdentifiers:(id)arg1 atIndexes:(id)arg2;
- (void)reloadItemsAtIndexes:(id)arg1;
- (void)insertItemsAtIndexes:(id)arg1;
- (void)reloadData;
@property(readonly, nonatomic) _Bool transcriptIsAnimating;
- (void)showTranscriptEnd;
@property(readonly, nonatomic) _Bool transcriptEndIsVisible;
@property(readonly, nonatomic) _Bool transcriptStartIsVisible;
- (double)_contentHeight;
- (struct CGPoint)_contentOffset;
@property(readonly, nonatomic) NSUUID *identifierOfLastDisplayedItem;
- (void)updateSuggestedUtterances:(id)arg1 forLanguage:(id)arg2;
- (void)_showSuggestionsIfNecessary;
- (void)statusBarFrameDidChange;
- (void)_updateViewTopMarginHeight;
- (void)_updateNavigationBarFrame;
- (_Bool)_isNavigationBarHidden;
- (id)_navigationBar;
- (void)_updateStatusBarRelatedAttributesAndUpdateContentInset:(_Bool)arg1;
- (struct CGRect)_statusBarFrame;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (id)_conversationItemList;
- (void)siriDidDeactivate;
- (void)siriDidTransitionFromState:(long long)arg1 event:(long long)arg2;
- (void)siriWillActivateFromSource:(long long)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)_runSirilandTransitionTestWithIterations:(int)arg1;
- (_Bool)_isRootViewController;
- (double)_navigationControllerContentOffsetAdjustment;
- (void)_setNavigationControllerContentInsetAdjustment:(struct UIEdgeInsets)arg1;
- (void)_updateGridAndPinHeight;
- (double)_bottomBarInset;
- (double)_topBarHeight;
- (void)_updateViewContentInset;
- (id)_collectionView;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)loadView;
- (void)dealloc;
- (void)invalidate;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) SVSTranscriptView *view;

@end

