//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SVSTranscriptViewController.h"

@interface SVSTranscriptViewController (SVSTranscriptStackViewController)
- (void)svscvc_setItemIdentifier:(id)arg1;
- (id)svscvc_itemIdentifier;
@end

