//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class SiriUIKeyline, UICollectionView;

@interface SVSTranscriptContentView : UIView
{
    SiriUIKeyline *_keyline;
    _Bool _keylineHidden;
    UICollectionView *_collectionView;
    UIView *_suggestionsView;
    double _topMargin;
}

@property(nonatomic) _Bool keylineHidden; // @synthesize keylineHidden=_keylineHidden;
@property(nonatomic) double topMargin; // @synthesize topMargin=_topMargin;
@property(retain, nonatomic) UIView *suggestionsView; // @synthesize suggestionsView=_suggestionsView;
@property(readonly, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 collectionView:(id)arg2;

@end

