//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SVSTranscriptStackViewController.h"

@interface SVSTranscriptStackViewController (SVSSirilandViewControllerAdditions)
- (void)svssvc_setConversation:(id)arg1;
- (id)svssvc_conversation;
@end

