//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSData, NSString, UIToolbar, UIWebView;

@interface BuddySimpleTCController : UIViewController
{
    UIToolbar *_toolbar;
    UIWebView *_webView;
    id <BuddyTCSubControllerDelegate> _delegate;
    NSData *_content;
}

@property(retain, nonatomic) NSData *content; // @synthesize content=_content;
@property(nonatomic) __weak id <BuddyTCSubControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)disagree:(id)arg1;
- (void)agree:(id)arg1;
- (void)updateLayout;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithTitle:(id)arg1 content:(id)arg2;

// Remaining properties
@property(retain, nonatomic) NSString *title;

@end

