//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PSListController.h"

#import "COSAppleIDLinkerDelegate.h"
#import "RemoteUIControllerDelegate.h"
#import "UIAlertViewDelegate.h"
#import "UITextFieldDelegate.h"

@class AASetupAssistantService, ACAccount, ACAccountStore, COSAppleIDLinker, NSSManager, NSString, RemoteUIController, UINavigationController, UITextField;

@interface COSAppleIDController : PSListController <UITextFieldDelegate, UIAlertViewDelegate, RemoteUIControllerDelegate, COSAppleIDLinkerDelegate>
{
    _Bool _hasFetchedGizmoiCloudInfo;
    _Bool _errorHasOccuredFetchingGizmoiCloudInfo;
    _Bool _gizmoIsLoggedIn;
    NSSManager *_nssManager;
    ACAccountStore *_accountStore;
    ACAccount *_existingAccount;
    AASetupAssistantService *_aaService;
    COSAppleIDLinker *_appleIDLinker;
    struct OpaqueCFHTTPCookieStorage *_cookieStorage;
    UITextField *_passwordTextField;
    id <NSObject> _textFieldTextDidChangeObserver;
    RemoteUIController *_iForgotRemoteController;
    UINavigationController *_iForgotController;
}

@property(retain, nonatomic) UINavigationController *iForgotController; // @synthesize iForgotController=_iForgotController;
@property(retain, nonatomic) RemoteUIController *iForgotRemoteController; // @synthesize iForgotRemoteController=_iForgotRemoteController;
@property(nonatomic) _Bool gizmoIsLoggedIn; // @synthesize gizmoIsLoggedIn=_gizmoIsLoggedIn;
@property(nonatomic) _Bool errorHasOccuredFetchingGizmoiCloudInfo; // @synthesize errorHasOccuredFetchingGizmoiCloudInfo=_errorHasOccuredFetchingGizmoiCloudInfo;
@property(nonatomic) _Bool hasFetchedGizmoiCloudInfo; // @synthesize hasFetchedGizmoiCloudInfo=_hasFetchedGizmoiCloudInfo;
@property(retain, nonatomic) id <NSObject> textFieldTextDidChangeObserver; // @synthesize textFieldTextDidChangeObserver=_textFieldTextDidChangeObserver;
@property(retain, nonatomic) UITextField *passwordTextField; // @synthesize passwordTextField=_passwordTextField;
@property(nonatomic) struct OpaqueCFHTTPCookieStorage *cookieStorage; // @synthesize cookieStorage=_cookieStorage;
@property(retain, nonatomic) COSAppleIDLinker *appleIDLinker; // @synthesize appleIDLinker=_appleIDLinker;
@property(retain, nonatomic) AASetupAssistantService *aaService; // @synthesize aaService=_aaService;
@property(retain, nonatomic) ACAccount *existingAccount; // @synthesize existingAccount=_existingAccount;
@property(retain, nonatomic) ACAccountStore *accountStore; // @synthesize accountStore=_accountStore;
@property(retain, nonatomic) NSSManager *nssManager; // @synthesize nssManager=_nssManager;
- (void).cxx_destruct;
- (void)remoteUIControllerDidDismiss:(id)arg1;
- (void)remoteUIController:(id)arg1 willPresentObjectModel:(id)arg2 modally:(_Bool)arg3;
- (void)remoteUIController:(id)arg1 willLoadRequest:(id)arg2;
- (void)_dismissiForgot;
- (void)_presentRemoteiForgotWithURL:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)appleIDLinker:(id)arg1 didFinishWithSuccess:(_Bool)arg2 error:(id)arg3;
- (id)viewControllerToPresentSecondFactorUIForAppleIDLinker:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)_textFieldValueDidChange:(id)arg1;
- (void)_loadiForgot;
- (void)tappedForgotButton;
- (void)stopNetworkRequest;
- (void)startNetworkRequest;
- (void)loggedInSuccessfully;
- (void)tappedSignIn;
- (void)enableSignInButton:(_Bool)arg1;
- (void)openSettingsApp;
- (void)_setPassword:(id)arg1 withSpecifier:(id)arg2;
- (id)_usernameForSpecifier:(id)arg1;
- (void)queryGizmoForiCloudInfo;
- (id)specifiers;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

