//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "COSSetupPageViewController.h"

#import "COSAppleIDLinkerDelegate.h"
#import "RemoteUIControllerDelegate.h"
#import "UITextFieldDelegate.h"

@class AASetupAssistantConfigResponse, AASetupAssistantService, ACAccount, ACAccountStore, COSAppleIDLinker, NSString, RemoteUIController, UIActivityIndicatorView, UIBarButtonItem, UIButton, UILabel, UINavigationController, UIScrollView, UITextField;

@interface COSAppleIDLoginViewController : COSSetupPageViewController <UITextFieldDelegate, RemoteUIControllerDelegate, COSAppleIDLinkerDelegate>
{
    NSString *_username;
    UIScrollView *_scroller;
    UILabel *_detailTitleLabel;
    UILabel *_detailLabel;
    UIButton *_infoButton;
    UILabel *_skipLabel;
    UILabel *_usernameLabel;
    UITextField *_passwordTextField;
    UILabel *_forgotPasswordLabel;
    id _passwordTextFieldDidChangeObserver;
    UIBarButtonItem *_nextNavBarButtonItem;
    UIActivityIndicatorView *_activityIndicator;
    UILabel *_verifyingLabel;
    ACAccountStore *_accountStore;
    ACAccount *_existingAccount;
    AASetupAssistantService *_aaService;
    COSAppleIDLinker *_appleIDLinker;
    AASetupAssistantConfigResponse *_configuration;
    RemoteUIController *_iForgotRemoteController;
    UINavigationController *_iForgotController;
    struct OpaqueCFHTTPCookieStorage *_cookieStorage;
}

+ (void)displayAlertNotConnectedToInternet;
+ (void)addHeadersAndCookiesToRequest:(id)arg1 cookieStorage:(struct OpaqueCFHTTPCookieStorage *)arg2;
+ (void)showAlertForLoginFailureWithError:(id)arg1 presentingViewController:(id)arg2;
+ (_Bool)controllerNeedsToRun;
@property(nonatomic) struct OpaqueCFHTTPCookieStorage *cookieStorage; // @synthesize cookieStorage=_cookieStorage;
@property(retain, nonatomic) UINavigationController *iForgotController; // @synthesize iForgotController=_iForgotController;
@property(retain, nonatomic) RemoteUIController *iForgotRemoteController; // @synthesize iForgotRemoteController=_iForgotRemoteController;
@property(retain, nonatomic) AASetupAssistantConfigResponse *configuration; // @synthesize configuration=_configuration;
@property(retain, nonatomic) COSAppleIDLinker *appleIDLinker; // @synthesize appleIDLinker=_appleIDLinker;
@property(retain, nonatomic) AASetupAssistantService *aaService; // @synthesize aaService=_aaService;
@property(retain, nonatomic) ACAccount *existingAccount; // @synthesize existingAccount=_existingAccount;
@property(retain, nonatomic) ACAccountStore *accountStore; // @synthesize accountStore=_accountStore;
@property(retain, nonatomic) UILabel *verifyingLabel; // @synthesize verifyingLabel=_verifyingLabel;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
@property(retain, nonatomic) UIBarButtonItem *nextNavBarButtonItem; // @synthesize nextNavBarButtonItem=_nextNavBarButtonItem;
@property(retain, nonatomic) id passwordTextFieldDidChangeObserver; // @synthesize passwordTextFieldDidChangeObserver=_passwordTextFieldDidChangeObserver;
@property(retain, nonatomic) UILabel *forgotPasswordLabel; // @synthesize forgotPasswordLabel=_forgotPasswordLabel;
@property(retain, nonatomic) UITextField *passwordTextField; // @synthesize passwordTextField=_passwordTextField;
@property(retain, nonatomic) UILabel *usernameLabel; // @synthesize usernameLabel=_usernameLabel;
@property(retain, nonatomic) UILabel *skipLabel; // @synthesize skipLabel=_skipLabel;
@property(retain, nonatomic) UIButton *infoButton; // @synthesize infoButton=_infoButton;
@property(retain, nonatomic) UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(retain, nonatomic) UILabel *detailTitleLabel; // @synthesize detailTitleLabel=_detailTitleLabel;
@property(retain, nonatomic) UIScrollView *scroller; // @synthesize scroller=_scroller;
@property(retain, nonatomic) NSString *username; // @synthesize username=_username;
- (void).cxx_destruct;
- (void)finishedActivating;
- (_Bool)holdBeforeDisplaying;
- (void)remoteUIControllerDidDismiss:(id)arg1;
- (void)remoteUIController:(id)arg1 willPresentObjectModel:(id)arg2 modally:(_Bool)arg3;
- (void)remoteUIController:(id)arg1 willLoadRequest:(id)arg2;
- (void)appleIDLinker:(id)arg1 didFinishWithSuccess:(_Bool)arg2 error:(id)arg3;
- (id)viewControllerToPresentSecondFactorUIForAppleIDLinker:(id)arg1;
- (void)_dismissiForgot;
- (void)_presentRemoteiForgotWithURL:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)_loadiForgot;
- (void)signInToAccountWithPassword:(id)arg1;
- (void)_signInToAccount;
- (void)signedInWithSuccess:(_Bool)arg1;
- (void)signInWithUsername:(id)arg1 password:(id)arg2;
- (void)allowUserInteractions:(_Bool)arg1;
- (void)stopNetworkRequest;
- (void)startNetworkRequest;
- (void)viewDidLayoutSubviews;
- (_Bool)contentViewIsInAdjustedScrollView;
- (void)viewDidLoad;
- (void)signInFailedWithError:(id)arg1;
- (void)loggedInSuccessfully;
- (void)tappedSkipButton:(id)arg1;
- (void)tappedNext;
- (void)passwordTextFieldDidChange:(id)arg1;
- (void)tappedForgotButton:(id)arg1;
- (void)keyboardWillBeHidden:(id)arg1;
- (void)keyboardWasShown:(id)arg1;
- (_Bool)allowSkipping;
- (id)detailText;
- (id)titleString;
- (void)dealloc;
- (id)init;
- (_Bool)controllerAllowsNavigatingBackTo;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <COSBuddyControllerDelegate> delegate;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

