//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AAGenericTermsUIRequest.h"

@class NRDevice, NSURLRequest;

@interface COSAAGenericTermsUIRequest : AAGenericTermsUIRequest
{
    _Bool _showWarranty;
    NRDevice *_device;
}

+ (id)deviceModelHeaderName;
+ (id)pairedClientInfoHeaderName;
+ (id)clientInfoHeaderForDevice:(id)arg1;
@property _Bool showWarranty; // @synthesize showWarranty=_showWarranty;
@property(retain) NRDevice *device; // @synthesize device=_device;
- (void).cxx_destruct;
@property(readonly) NSURLRequest *urlRequest;
- (id)initWithGizmoDevice:(id)arg1 showWarranty:(_Bool)arg2;

@end

