//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PSListController.h"

@class NRDevice, NSNumber, NSObject<OS_dispatch_semaphore>, NSSManager;

@interface COSAboutController : PSListController
{
    _Bool _hasFetchedAboutInfo;
    _Bool _errorHasOccurred;
    NSSManager *_nssManager;
    NRDevice *_device;
    NSObject<OS_dispatch_semaphore> *_registrySemaphore;
    NSNumber *_numberOfApps;
    NSNumber *_numberOfSongs;
    NSNumber *_numberOfPhotos;
    unsigned long long _storageAvailable;
}

@property(nonatomic) unsigned long long storageAvailable; // @synthesize storageAvailable=_storageAvailable;
@property(retain, nonatomic) NSNumber *numberOfPhotos; // @synthesize numberOfPhotos=_numberOfPhotos;
@property(retain, nonatomic) NSNumber *numberOfSongs; // @synthesize numberOfSongs=_numberOfSongs;
@property(retain, nonatomic) NSNumber *numberOfApps; // @synthesize numberOfApps=_numberOfApps;
@property(nonatomic) _Bool errorHasOccurred; // @synthesize errorHasOccurred=_errorHasOccurred;
@property(nonatomic) _Bool hasFetchedAboutInfo; // @synthesize hasFetchedAboutInfo=_hasFetchedAboutInfo;
@property(retain, nonatomic) NSObject<OS_dispatch_semaphore> *registrySemaphore; // @synthesize registrySemaphore=_registrySemaphore;
@property(retain, nonatomic) NRDevice *device; // @synthesize device=_device;
@property(retain, nonatomic) NSSManager *nssManager; // @synthesize nssManager=_nssManager;
- (void).cxx_destruct;
- (void)showUserManual:(id)arg1;
- (void)tappedAppleLegalLink;
- (id)getBTAddress:(id)arg1;
- (id)getWiFiAddress:(id)arg1;
- (id)getSerialNumber:(id)arg1;
- (id)getDeviceModel:(id)arg1;
- (id)getSystemVersion:(id)arg1;
- (id)getStorageCapacity:(id)arg1;
- (void)setDeviceName:(id)arg1 specifier:(id)arg2;
- (id)getDeviceName:(id)arg1;
- (id)getStorageAvailable:(id)arg1;
- (id)getNumberOfApps:(id)arg1;
- (id)getNumberOfPhotos:(id)arg1;
- (id)getNumberOfSongs:(id)arg1;
- (id)guardedUint64StringValue:(unsigned long long)arg1;
- (id)dash;
- (id)specifiers;
- (void)viewWillDisappear:(_Bool)arg1;
- (id)init;

@end

