//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AAUIAccountRepairRemoteUIDelegate.h"

@class AAUIAccountRepairRemoteUI, ACAccount, ACAccountStore, NSString, RUIStyle;

@interface COSAppleIDLinker : NSObject <AAUIAccountRepairRemoteUIDelegate>
{
    ACAccountStore *_accountStore;
    ACAccount *_account;
    AAUIAccountRepairRemoteUI *_secondFactorRemoteUI;
    id <COSAppleIDLinkerDelegate> _delegate;
    RUIStyle *_ruiStyle;
}

@property(retain, nonatomic) RUIStyle *ruiStyle; // @synthesize ruiStyle=_ruiStyle;
@property(nonatomic) __weak id <COSAppleIDLinkerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)accountRepairRemoteUI:(id)arg1 headersForRequest:(id)arg2;
- (void)accountRepairRemoteUI:(id)arg1 willPresentModalNavigationController:(id)arg2;
- (void)accountRepairRemoteUI:(id)arg1 didReceiveObjectModel:(id)arg2;
- (void)accountRepairRemoteUI:(id)arg1 account:(id)arg2 didFinishWithSuccess:(_Bool)arg3;
- (void)accountRepairRemoteUIWillDismiss:(id)arg1;
- (void)accountRepairRemoteUIWillAppear:(id)arg1;
- (void)_startSecondFactorVerificationUsingCookieHeaders:(id)arg1;
- (void)start;
- (void)dealloc;
- (id)initWithAccount:(id)arg1 accountStore:(id)arg2 password:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

