//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "COSSetupPageViewController.h"

@class NSString, UIImage;

@interface COSAboutViewController : COSSetupPageViewController
{
    NSString *_titleString;
    UIImage *_headerGlyph;
}

@property(retain, nonatomic) UIImage *headerGlyph; // @synthesize headerGlyph=_headerGlyph;
@property(retain, nonatomic) NSString *titleString; // @synthesize titleString=_titleString;
- (void).cxx_destruct;
- (unsigned long long)supportedInterfaceOrientations;
- (void)presentWithController:(id)arg1;
- (void)donePressed;
- (id)init;

@end

