//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class COSAppleIDLinker, NSError, UIViewController;

@protocol COSAppleIDLinkerDelegate <NSObject>
- (UIViewController *)viewControllerToPresentSecondFactorUIForAppleIDLinker:(COSAppleIDLinker *)arg1;
- (void)appleIDLinker:(COSAppleIDLinker *)arg1 didFinishWithSuccess:(_Bool)arg2 error:(NSError *)arg3;

@optional
- (void)appleIDLinkerDidFinishSecondFactorAuthentication:(COSAppleIDLinker *)arg1;
- (void)appleIDLinkerWillStartSecondFactorAuthentication:(COSAppleIDLinker *)arg1;
@end

