//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PSListController.h"

@interface COSAutomaticDownloadsController : PSListController
{
    _Bool _alwaysInstall;
}

@property(nonatomic) _Bool alwaysInstall; // @synthesize alwaysInstall=_alwaysInstall;
- (void)setAutomaticDownloadsEnabled:(id)arg1 specifier:(id)arg2;
- (id)automaticDownloadsEnabled:(id)arg1;
- (id)specifiers;
- (id)init;

@end

