//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIViewController<COSBuddyController>;

@protocol COSBuddyControllerDelegate <NSObject>
@property(nonatomic) _Bool combinedMessagesSignInFailed;
@property(nonatomic) _Bool hasSignedInToICloud;
- (void)displayUpdateControllerAnimated:(_Bool)arg1 completion:(void (^)(void))arg2;
- (void)displayCompanionTooOldPairingFailureAlertWithDismissalHandler:(void (^)(void))arg1;
- (void)buddyControllerCancelAnyHold;
- (void)buddyControllerReleaseHold:(id <COSBuddyController>)arg1;
- (id <COSBuddyController>)nextControllerAfterHold;
- (id <COSBuddyController>)topBuddyController;
- (UIViewController<COSBuddyController> *)popToBuddyControllerWithClass:(Class)arg1 animated:(_Bool)arg2;
- (void)buddyControllerDone:(id <COSBuddyController>)arg1 nextControllerClass:(Class)arg2;
- (void)buddyControllerDone:(id <COSBuddyController>)arg1;
@end

