//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NBBackup, NBManager, NSArray;

@interface COSBackupManager : NSObject
{
    _Bool _isRestoringFromBackup;
    NBManager *_backupController;
    NBBackup *_activeBackup;
    NSArray *_localBackups;
}

+ (id)sharedBackupManager;
@property(retain, nonatomic) NSArray *localBackups; // @synthesize localBackups=_localBackups;
@property(retain, nonatomic) NBBackup *activeBackup; // @synthesize activeBackup=_activeBackup;
@property(readonly, nonatomic) _Bool isRestoringFromBackup; // @synthesize isRestoringFromBackup=_isRestoringFromBackup;
@property(retain, nonatomic) NBManager *backupController; // @synthesize backupController=_backupController;
- (void).cxx_destruct;
- (id)backups;
- (_Bool)hasBackups;
- (void)reloadBackups;
- (id)init;

@end

