//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PSBadgedTableCell.h"

@class UIImageView;

@interface COSBadgedTableCell : PSBadgedTableCell
{
    UIImageView *_badgeImageView;
}

+ (id)badgeNumberLabelHighlightedTextColor;
+ (id)badgeNumberLabelTextColor;
+ (id)unreadBubbleHighlightedImage;
+ (id)unreadBubbleImage;
+ (double)badgePadding;
+ (id)reuseIdentifierForClassAndType:(long long)arg1;
- (void).cxx_destruct;

@end

