//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UINavigationController, UIViewController;

@protocol COSBuddyController <NSObject>
- (void)setDelegate:(id <COSBuddyControllerDelegate>)arg1;
- (id <COSBuddyControllerDelegate>)delegate;

@optional
+ (_Bool)controllerNeedsToRunForBuddyControllerDelegate:(id <COSBuddyControllerDelegate>)arg1;
+ (_Bool)controllerNeedsToRun;
- (_Bool)holdBeforeDisplaying;
- (UIViewController *)viewController;
- (void)removeFromNavHierarchyOf:(UINavigationController *)arg1;
- (_Bool)controllerAllowsNavigatingBackFrom;
- (_Bool)controllerAllowsNavigatingBackTo;
@end

