//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PSRootController.h"

@interface COSBuddyNavigationController : PSRootController
{
    id <COSBuddyNavigationControllerDelegate> _buddyNavDelegate;
}

@property(nonatomic) id <COSBuddyNavigationControllerDelegate> buddyNavDelegate; // @synthesize buddyNavDelegate=_buddyNavDelegate;
- (unsigned long long)supportedInterfaceOrientations;
- (id)popViewControllerAnimated:(_Bool)arg1;
- (_Bool)_usesTransitionController;

@end

