//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKUIClientContext.h"

@class SKUILocalizedStringDictionary;

@interface COSClientContext : SKUIClientContext
{
    SKUILocalizedStringDictionary *_localizedStrings;
}

- (void).cxx_destruct;
- (id)localizedStringForKey:(id)arg1 inTable:(id)arg2;
- (void)getDefaultMetricsControllerWithCompletionBlock:(CDUnknownBlockType)arg1;
- (id)initWithConfigurationDictionary:(id)arg1;

@end

