//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "COSBuddyController.h"

@class COSWatchView, NSString, UIButton, UILabel, UITapGestureRecognizer;

@interface COSCrownOrientationChoiceViewController : UIViewController <COSBuddyController>
{
    id <COSBuddyControllerDelegate> _delegate;
    UILabel *_crownTitleLabel;
    UILabel *_crownTitleDetailLabel;
    UIButton *_leftCrownButton;
    UIButton *_rightCrownButton;
    COSWatchView *_crownChoiceView;
    UITapGestureRecognizer *_crownTapRecognizer;
    UILabel *_crownDetailLabel;
}

@property(retain, nonatomic) UILabel *crownDetailLabel; // @synthesize crownDetailLabel=_crownDetailLabel;
@property(retain, nonatomic) UITapGestureRecognizer *crownTapRecognizer; // @synthesize crownTapRecognizer=_crownTapRecognizer;
@property(retain, nonatomic) COSWatchView *crownChoiceView; // @synthesize crownChoiceView=_crownChoiceView;
@property(retain, nonatomic) UIButton *rightCrownButton; // @synthesize rightCrownButton=_rightCrownButton;
@property(retain, nonatomic) UIButton *leftCrownButton; // @synthesize leftCrownButton=_leftCrownButton;
@property(retain, nonatomic) UILabel *crownTitleDetailLabel; // @synthesize crownTitleDetailLabel=_crownTitleDetailLabel;
@property(retain, nonatomic) UILabel *crownTitleLabel; // @synthesize crownTitleLabel=_crownTitleLabel;
@property(nonatomic) __weak id <COSBuddyControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)madeCrownSelection:(id)arg1;
- (void)tappedCrownImage:(id)arg1;
- (void)_selectedCrownOnRight:(_Bool)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

