//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "COSOptinViewController.h"

@interface COSDiagnosticsOptinViewController : COSOptinViewController
{
}

+ (_Bool)controllerNeedsToRun;
- (void)selectedAboutDetail:(id)arg1;
- (id)detailTitleString;
- (id)aboutButtonString;
- (id)alternateButtonString;
- (id)suggestedButtonString;
- (void)applyConfirmedOptin:(_Bool)arg1;
- (void)selecedOptinChoice:(id)arg1;
- (id)imageResource;
- (id)detailString;
- (id)titleString;
- (id)init;

@end

