//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PSListController.h"

#import "MCProfileConnectionObserver.h"

@class NPKCompanionAgentConnection, NSString, PUConnection;

@interface COSGeneralSettingsController : PSListController <MCProfileConnectionObserver>
{
    PUConnection *_unlockConnection;
    _Bool _hasPaymentPasses;
    _Bool _remoteUnlockEnabled;
    _Bool _onlyRemoteUnlockEnabled;
    NPKCompanionAgentConnection *_passbookConnection;
}

@property(nonatomic, getter=isOnlyRemoteUnlockEnabled) _Bool onlyRemoteUnlockEnabled; // @synthesize onlyRemoteUnlockEnabled=_onlyRemoteUnlockEnabled;
@property(nonatomic, getter=isRemoteUnlockEnabled) _Bool remoteUnlockEnabled; // @synthesize remoteUnlockEnabled=_remoteUnlockEnabled;
@property(nonatomic) _Bool hasPaymentPasses; // @synthesize hasPaymentPasses=_hasPaymentPasses;
@property(retain, nonatomic) NPKCompanionAgentConnection *passbookConnection; // @synthesize passbookConnection=_passbookConnection;
- (void).cxx_destruct;
- (void)cancelDisableWristDetect:(id)arg1;
- (void)confirmDisableWristDetect:(id)arg1;
- (void)_showWristDetectDisableConfirmation;
- (void)_setWristDetectFooterText:(id)arg1;
- (id)wristDetectValue:(id)arg1;
- (void)setWristDetectValue:(id)arg1 specifier:(id)arg2;
- (void)_checkWristDetectStatus;
- (void)profileConnectionDidReceiveEffectiveSettingsChangedNotification:(id)arg1 userInfo:(id)arg2;
- (void)_gotOnlyRemoteUnlockState:(_Bool)arg1;
- (void)_gotUnlockState:(_Bool)arg1;
- (void)handleURL:(id)arg1;
- (id)getGizmoWristChoice:(id)arg1;
- (id)specifiers;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

