//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class AVPlayerItem, AVQueuePlayer, COSWatchView, UIButton, UILabel;

@interface COSGizmoWristSelectionView : UIView
{
    _Bool _enabled;
    _Bool _wantsToPlay;
    _Bool _assetsLoaded;
    id <COSGizmoWristSelectionViewDelegate> _delegate;
    unsigned long long _mode;
    UILabel *_pairedTitleLabel;
    UILabel *_detailLabel;
    UILabel *_wristTitleLabel;
    UIButton *_leftButton;
    UIButton *_rightButton;
    UIButton *_setupDevice;
    UIButton *_setupAsNewDevice;
    UIButton *_restoreFromBackup;
    UIButton *_updateDevice;
    UIButton *_skipUpdate;
    COSWatchView *_watchView;
    UIView *_deviceInsignia;
    AVQueuePlayer *_player;
    AVPlayerItem *_magicCodeOutro;
    AVPlayerItem *_magicCodeOutroPerMaterial;
}

+ (id)_fakeBackButtonItemForDelegate:(id)arg1 withAction:(SEL)arg2;
@property(retain, nonatomic) AVPlayerItem *magicCodeOutroPerMaterial; // @synthesize magicCodeOutroPerMaterial=_magicCodeOutroPerMaterial;
@property(retain, nonatomic) AVPlayerItem *magicCodeOutro; // @synthesize magicCodeOutro=_magicCodeOutro;
@property(retain, nonatomic) AVQueuePlayer *player; // @synthesize player=_player;
@property(retain, nonatomic) UIView *deviceInsignia; // @synthesize deviceInsignia=_deviceInsignia;
@property(retain, nonatomic) COSWatchView *watchView; // @synthesize watchView=_watchView;
@property(retain, nonatomic) UIButton *skipUpdate; // @synthesize skipUpdate=_skipUpdate;
@property(retain, nonatomic) UIButton *updateDevice; // @synthesize updateDevice=_updateDevice;
@property(retain, nonatomic) UIButton *restoreFromBackup; // @synthesize restoreFromBackup=_restoreFromBackup;
@property(retain, nonatomic) UIButton *setupAsNewDevice; // @synthesize setupAsNewDevice=_setupAsNewDevice;
@property(retain, nonatomic) UIButton *setupDevice; // @synthesize setupDevice=_setupDevice;
@property(retain, nonatomic) UIButton *rightButton; // @synthesize rightButton=_rightButton;
@property(retain, nonatomic) UIButton *leftButton; // @synthesize leftButton=_leftButton;
@property(retain, nonatomic) UILabel *wristTitleLabel; // @synthesize wristTitleLabel=_wristTitleLabel;
@property(retain, nonatomic) UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(retain, nonatomic) UILabel *pairedTitleLabel; // @synthesize pairedTitleLabel=_pairedTitleLabel;
@property(nonatomic) _Bool assetsLoaded; // @synthesize assetsLoaded=_assetsLoaded;
@property(nonatomic) _Bool wantsToPlay; // @synthesize wantsToPlay=_wantsToPlay;
@property(nonatomic) unsigned long long mode; // @synthesize mode=_mode;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(nonatomic) __weak id <COSGizmoWristSelectionViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)setMode:(unsigned long long)arg1 animated:(_Bool)arg2;
- (void)_moveFromUpdateToRestoreChoice;
- (void)_moveBackwardsToRestoreChoice;
- (void)_moveBackwardsToWristChoice;
- (void)_moveForwardToWristChoice;
- (void)showOptionsAnimated:(_Bool)arg1;
- (void)showInsignaAnimated:(_Bool)arg1;
- (void)abortPairing;
- (void)selectedSkipUpdate:(id)arg1;
- (void)selectedUpdateDevice:(id)arg1;
- (void)selectedRestoreFromBackup:(id)arg1;
- (void)selectedSetupNewDevice:(id)arg1;
- (void)madeWristSelection:(id)arg1;
- (void)returnToRestoreSelection;
- (void)layoutSubviews;
- (void)setButtonsEnabled:(_Bool)arg1;
- (void)playerItemDidReachEnd:(id)arg1;
- (void)dealloc;
- (void)addItemWithURL:(id)arg1 afterPlayerItem:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)initWithFrame:(struct CGRect)arg1;

@end

