//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "COSBuddyController.h"
#import "COSGetStartedDelegate.h"
#import "COSGizmoWristSelectionViewDelegate.h"
#import "COSInternalManualPairingDelegate.h"
#import "COSMagicCodeScannerDelegate.h"
#import "COSManualSecurePairingDelegate.h"
#import "PKCaptureDelegate.h"
#import "RUILoaderDelegate.h"
#import "RUIObjectModelDelegate.h"

@class COSBarcodeScannerView, COSGizmoWristSelectionView, COSInternalManualPairingViewController, COSMagicCodeScanner, COSScannerActivityView, COSSecurePairingFlowViewController, COSUnpairingViewController, NRDevice, NSString, NSTimer, RUIObjectModel, UIButton, UIImageView, UILabel, UINavigationBar;

@interface COSGizmoCaptureViewController : UIViewController <PKCaptureDelegate, COSGetStartedDelegate, RUILoaderDelegate, RUIObjectModelDelegate, COSGizmoWristSelectionViewDelegate, COSInternalManualPairingDelegate, COSManualSecurePairingDelegate, COSMagicCodeScannerDelegate, COSBuddyController>
{
    _Bool _scanningForQRCode;
    _Bool _noCameraMode;
    id <COSBuddyControllerDelegate> _delegate;
    COSMagicCodeScanner *_magicCodeScanner;
    COSBarcodeScannerView *_captureSession;
    UIImageView *_overlayiew;
    NSTimer *_discoveryExpiryTimer;
    NSTimer *_scannerExpiryTimer;
    NSString *_scannedCode;
    NSString *_versionString;
    NSString *_pairingVersionString;
    NSString *_deviceSetupName;
    NSString *_oobIdentifier;
    UILabel *_gizmoMessage;
    UILabel *_instruction;
    UILabel *_instructionDetail;
    UIButton *_havingTroubleButton;
    COSScannerActivityView *_activityView;
    COSSecurePairingFlowViewController *_manualPairingController;
    COSInternalManualPairingViewController *_internalPairingController;
    COSUnpairingViewController *_unpairingVC;
    RUIObjectModel *_objectModel;
    COSGizmoWristSelectionView *_wristSelectionView;
    NRDevice *_scannedDevice;
    UINavigationBar *_transparentNavigationBar;
}

@property(nonatomic) _Bool noCameraMode; // @synthesize noCameraMode=_noCameraMode;
@property(retain, nonatomic) UINavigationBar *transparentNavigationBar; // @synthesize transparentNavigationBar=_transparentNavigationBar;
@property(retain, nonatomic) NRDevice *scannedDevice; // @synthesize scannedDevice=_scannedDevice;
@property(retain, nonatomic) COSGizmoWristSelectionView *wristSelectionView; // @synthesize wristSelectionView=_wristSelectionView;
@property(retain, nonatomic) RUIObjectModel *objectModel; // @synthesize objectModel=_objectModel;
@property(retain, nonatomic) COSUnpairingViewController *unpairingVC; // @synthesize unpairingVC=_unpairingVC;
@property(retain, nonatomic) COSInternalManualPairingViewController *internalPairingController; // @synthesize internalPairingController=_internalPairingController;
@property(retain, nonatomic) COSSecurePairingFlowViewController *manualPairingController; // @synthesize manualPairingController=_manualPairingController;
@property(retain, nonatomic) COSScannerActivityView *activityView; // @synthesize activityView=_activityView;
@property(retain, nonatomic) UIButton *havingTroubleButton; // @synthesize havingTroubleButton=_havingTroubleButton;
@property(retain, nonatomic) UILabel *instructionDetail; // @synthesize instructionDetail=_instructionDetail;
@property(retain, nonatomic) UILabel *instruction; // @synthesize instruction=_instruction;
@property(retain, nonatomic) UILabel *gizmoMessage; // @synthesize gizmoMessage=_gizmoMessage;
@property(nonatomic) _Bool scanningForQRCode; // @synthesize scanningForQRCode=_scanningForQRCode;
@property(copy, nonatomic) NSString *oobIdentifier; // @synthesize oobIdentifier=_oobIdentifier;
@property(copy, nonatomic) NSString *deviceSetupName; // @synthesize deviceSetupName=_deviceSetupName;
@property(copy, nonatomic) NSString *pairingVersionString; // @synthesize pairingVersionString=_pairingVersionString;
@property(copy, nonatomic) NSString *versionString; // @synthesize versionString=_versionString;
@property(copy, nonatomic) NSString *scannedCode; // @synthesize scannedCode=_scannedCode;
@property(retain, nonatomic) NSTimer *scannerExpiryTimer; // @synthesize scannerExpiryTimer=_scannerExpiryTimer;
@property(retain, nonatomic) NSTimer *discoveryExpiryTimer; // @synthesize discoveryExpiryTimer=_discoveryExpiryTimer;
@property(retain, nonatomic) UIImageView *overlayiew; // @synthesize overlayiew=_overlayiew;
@property(retain, nonatomic) COSBarcodeScannerView *captureSession; // @synthesize captureSession=_captureSession;
@property(retain, nonatomic) COSMagicCodeScanner *magicCodeScanner; // @synthesize magicCodeScanner=_magicCodeScanner;
@property(nonatomic) __weak id <COSBuddyControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dismissSetupFlow:(id)arg1;
- (void)deviceDidDecode:(id)arg1;
- (void)_scannerSatTooLong:(id)arg1;
- (void)_extendScannerTimeout;
- (void)_cancelScannerTimeout;
- (void)timedoutInDiscoveryPhase:(id)arg1;
- (void)_cancelDiscoveryExpiryTimer;
- (void)back:(id)arg1;
- (void)nanoRegistryStatusChanged:(id)arg1;
- (void)deviceDidBeginActivation:(id)arg1;
- (void)setupWristSelectionView;
- (void)objectModelPressedBack:(id)arg1;
- (id)parentViewControllerForObjectModel:(id)arg1;
- (void)objectModel:(id)arg1 pressedLink:(id)arg2 httpMethod:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)objectModel:(id)arg1 elementDidChange:(id)arg2;
- (void)loader:(id)arg1 didReceiveHTTPResponse:(id)arg2;
- (void)loader:(id)arg1 receivedObjectModel:(id)arg2 actionSignal:(int)arg3;
- (void)loader:(id)arg1 didFailWithError:(id)arg2;
- (id)pairingDevice;
- (void)pair;
- (void)abortPairingForEvent:(unsigned long long)arg1;
- (void)enteredCompatibilityState:(id)arg1;
- (void)didBeginToPair:(id)arg1;
- (void)pairingRequestAttempted:(id)arg1;
- (void)_fireLockOnAnimation;
- (void)receivedData:(id)arg1;
- (void)captureOutput:(id)arg1 didOutputMetadataObjects:(id)arg2 fromConnection:(id)arg3;
- (void)processScannedCode;
- (void)beganActivating;
- (void)alternatePathBeganConnecting:(id)arg1;
- (void)cancelledSecurePairing;
- (void)completedSecurePairing;
- (void)processScannedCodeForManualPairing;
- (void)setManualPairingScannedCode:(id)arg1;
- (void)cancelledManualPairing;
- (void)doneManualPairing;
- (void)setupScanningEngine;
- (void)presentNoCameraMode;
- (void)presentSecurePairingMode;
- (void)_presentInternalManualMode:(id)arg1;
- (void)selectedUpdateChoice;
- (void)proceedToRestore;
- (void)returnToRestoreChoice;
- (void)selectedRestoreChoice;
- (void)showBackToPairingButton;
- (void)donePickedLeftArm:(_Bool)arg1;
- (void)dismissCaptureViews;
- (void)didReceiveMemoryWarning;
- (void)viewDidLayoutSubviews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)presentUnpairingViewControllerAnimated:(_Bool)arg1;
- (void)_popToCaptureView;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (_Bool)hasStartedPairing;
- (void)reset;
- (void)invalidateTimers;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

