//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationController.h"

#import "COSGetStartedDelegate.h"

@class COSGetStartedInternalViewController, COSUnpairingViewController, NSString;

@interface COSGetStartedViewController : UINavigationController <COSGetStartedDelegate>
{
    id <COSGetStartedViewControllerDelegate> _getStartedDelegate;
    COSGetStartedInternalViewController *_internalController;
    COSUnpairingViewController *_unpairingVC;
}

@property(retain, nonatomic) COSUnpairingViewController *unpairingVC; // @synthesize unpairingVC=_unpairingVC;
@property(retain, nonatomic) COSGetStartedInternalViewController *internalController; // @synthesize internalController=_internalController;
@property(nonatomic) __weak id <COSGetStartedViewControllerDelegate> getStartedDelegate; // @synthesize getStartedDelegate=_getStartedDelegate;
- (void).cxx_destruct;
- (void)stopAnimating;
- (void)startAnimating;
- (void)nanoRegistryStatusChanged:(id)arg1;
- (void)showConnectivityAlert;
- (void)userTappedStart;
- (void)tappedStartInternal;
- (void)presentUnpairingViewControllerAnimated:(_Bool)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)_setOrientationModeForSize:(struct CGSize)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (id)init;
- (unsigned long long)supportedInterfaceOrientations;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

