//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PSYProgressObserverDelegate.h"

@class NSHashTable, NSObject<OS_dispatch_queue>, NSString, PSYProgressObserver;

@interface COSInitialSyncMonitor : NSObject <PSYProgressObserverDelegate>
{
    PSYProgressObserver *_progressObserver;
    NSObject<OS_dispatch_queue> *_queue;
    NSHashTable *_observers;
}

@property(retain, nonatomic) NSHashTable *observers; // @synthesize observers=_observers;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) PSYProgressObserver *progressObserver; // @synthesize progressObserver=_progressObserver;
- (void).cxx_destruct;
- (void)removeAllObservers;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)progressObserver:(id)arg1 didFinishActivity:(id)arg2 withError:(id)arg3;
- (void)progressObserverDidChangeProgress:(id)arg1;
- (void)progressObserverDidChangeState:(id)arg1;
- (void)stopMonitoring;
- (void)beginMonitoring;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

