//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "COSAppleIDLoginViewController.h"

@interface COSiMessageLoginViewController : COSAppleIDLoginViewController
{
}

+ (id)primaryiMessageAccount;
+ (_Bool)controllerNeedsToRunForBuddyControllerDelegate:(id)arg1;
- (void)signInToAccountWithPassword:(id)arg1;
- (void)signInFailedWithError:(id)arg1;
- (void)loggedInSuccessfully;
- (_Bool)allowSkipping;
- (id)detailText;
- (id)username;
- (id)titleString;
- (_Bool)holdBeforeDisplaying;
- (_Bool)controllerAllowsNavigatingBackTo;

@end

