//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol COSInternalManualPairingDelegate <NSObject>
- (void)processScannedCodeForManualPairing;
- (void)setManualPairingScannedCode:(NSString *)arg1;
- (void)cancelledManualPairing;
- (void)doneManualPairing;
@end

