//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PSListController.h"

@class NSSManager, NSString, PSSpecifier;

@interface COSLegalController : PSListController
{
    _Bool _hasFetchedDocuments;
    _Bool _errorHasOccurred;
    NSSManager *_nssManager;
    PSSpecifier *_legalNoticesSpecifier;
    PSSpecifier *_licenseSpecifier;
    PSSpecifier *_warrantyPointerSpecifier;
    PSSpecifier *_rfExposureSpecifier;
    NSString *_legalNoticesMarkup;
    NSString *_licenseMarkup;
    NSString *_rfExposureMarkup;
    PSSpecifier *_remoteLoadingSpecifier;
}

@property(retain, nonatomic) PSSpecifier *remoteLoadingSpecifier; // @synthesize remoteLoadingSpecifier=_remoteLoadingSpecifier;
@property(retain, nonatomic) NSString *rfExposureMarkup; // @synthesize rfExposureMarkup=_rfExposureMarkup;
@property(retain, nonatomic) NSString *licenseMarkup; // @synthesize licenseMarkup=_licenseMarkup;
@property(retain, nonatomic) NSString *legalNoticesMarkup; // @synthesize legalNoticesMarkup=_legalNoticesMarkup;
@property(nonatomic) _Bool errorHasOccurred; // @synthesize errorHasOccurred=_errorHasOccurred;
@property(nonatomic) _Bool hasFetchedDocuments; // @synthesize hasFetchedDocuments=_hasFetchedDocuments;
@property(retain, nonatomic) PSSpecifier *rfExposureSpecifier; // @synthesize rfExposureSpecifier=_rfExposureSpecifier;
@property(retain, nonatomic) PSSpecifier *warrantyPointerSpecifier; // @synthesize warrantyPointerSpecifier=_warrantyPointerSpecifier;
@property(retain, nonatomic) PSSpecifier *licenseSpecifier; // @synthesize licenseSpecifier=_licenseSpecifier;
@property(retain, nonatomic) PSSpecifier *legalNoticesSpecifier; // @synthesize legalNoticesSpecifier=_legalNoticesSpecifier;
@property(retain, nonatomic) NSSManager *nssManager; // @synthesize nssManager=_nssManager;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)stopSpinner;
- (void)startSpinnerInCellForSpecifier:(id)arg1;
- (id)specifiers;
- (void)handleLegalDocuments:(id)arg1 error:(id)arg2;
- (void)queryGizmoForLegalDocuments;
- (id)init;

@end

