//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class AVCaptureDevice, AVCaptureSession, AVCaptureVideoPreviewLayer, CALayer, NSObject<OS_dispatch_queue>, UITapGestureRecognizer;

@interface COSMagicCodeScanner : UIView
{
    AVCaptureSession *_session;
    AVCaptureDevice *_device;
    AVCaptureVideoPreviewLayer *_previewLayer;
    NSObject<OS_dispatch_queue> *_queue;
    struct HCImagePerspectiveReader *_reader;
    unsigned long long _readerUVWidth;
    unsigned long long _readerUVHeight;
    unsigned long long _readerUVBytesPerRow;
    double _watermark;
    struct __CFArray *_pixelBufferPyramidArray;
    struct OpaqueVTPixelTransferSession *_pixelTransferSession;
    struct CGRect _interestRect;
    _Bool _canUseCamera;
    _Bool _isScanningForCode;
    id <COSMagicCodeScannerDelegate> _delegate;
    UITapGestureRecognizer *_debugUIRecognizer;
    CALayer *_progressBGLayer;
    CALayer *_progressLayer;
}

@property(retain, nonatomic) CALayer *progressLayer; // @synthesize progressLayer=_progressLayer;
@property(retain, nonatomic) CALayer *progressBGLayer; // @synthesize progressBGLayer=_progressBGLayer;
@property(retain, nonatomic) UITapGestureRecognizer *debugUIRecognizer; // @synthesize debugUIRecognizer=_debugUIRecognizer;
@property(nonatomic) _Bool isScanningForCode; // @synthesize isScanningForCode=_isScanningForCode;
@property(readonly, nonatomic) _Bool canUseCamera; // @synthesize canUseCamera=_canUseCamera;
@property(nonatomic) __weak id <COSMagicCodeScannerDelegate> delegate; // @synthesize delegate=_delegate;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)handleRuntimeError:(id)arg1;
- (void)stopRunning;
- (void)startRunning;
- (void)_changeCameraConfiguration;
- (void)captureOutput:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
- (void)layoutSubviews;
- (void)setupCameraSession;
- (void)toggleDebugUI:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

