//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PSListController.h"

@class NSArray, NSDictionary;

@interface COSNotificationsController : PSListController
{
    NSArray *_bbSections;
    NSDictionary *_inheritedWhiteList;
}

@property(retain, nonatomic) NSDictionary *inheritedWhiteList; // @synthesize inheritedWhiteList=_inheritedWhiteList;
@property(retain, nonatomic) NSArray *bbSections; // @synthesize bbSections=_bbSections;
- (void).cxx_destruct;
- (id)showOnGizmoState:(id)arg1;
- (void)setShowOnGizmoState:(id)arg1 specifier:(id)arg2;
- (id)specifiersFromBBSections;
- (void)cleanBBSections;
- (void)refreshBBSections;
- (void)setupWhitelistFromInheritedSpecifiers;
- (void)setNotificationsIndicatorActive:(id)arg1 specifier:(id)arg2;
- (id)notificationsIndicatorActive:(id)arg1;
- (id)additionalSpecifiers;
- (id)localizedPrefsStringForString:(id)arg1;
- (id)hardcodedSpecifiers;
- (void)showController:(id)arg1 animate:(_Bool)arg2;
- (id)specifiers;
- (void)reloadSpecifiers;
- (void)becomeActive:(id)arg1;
- (void)dealloc;
- (id)init;

@end

