//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "COSSetupPageViewController.h"

@class COSWatchView, UIButton, UILabel, UIScrollView;

@interface COSOptinViewController : COSSetupPageViewController
{
    _Bool _fyiMode;
    UIButton *_suggestedChoiceButton;
    UIButton *_alternateChoiceButton;
    UIButton *_moreOptionsButton;
    UIButton *_aboutButton;
    UIScrollView *_scroller;
    UILabel *_detailTitleLabel;
    UILabel *_detailLabel;
    COSWatchView *_watchView;
}

@property(retain, nonatomic) COSWatchView *watchView; // @synthesize watchView=_watchView;
@property(retain, nonatomic) UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(retain, nonatomic) UILabel *detailTitleLabel; // @synthesize detailTitleLabel=_detailTitleLabel;
@property(retain, nonatomic) UIScrollView *scroller; // @synthesize scroller=_scroller;
@property(nonatomic) _Bool fyiMode; // @synthesize fyiMode=_fyiMode;
@property(readonly, nonatomic) UIButton *aboutButton; // @synthesize aboutButton=_aboutButton;
@property(readonly, nonatomic) UIButton *moreOptionsButton; // @synthesize moreOptionsButton=_moreOptionsButton;
@property(readonly, nonatomic) UIButton *alternateChoiceButton; // @synthesize alternateChoiceButton=_alternateChoiceButton;
@property(readonly, nonatomic) UIButton *suggestedChoiceButton; // @synthesize suggestedChoiceButton=_suggestedChoiceButton;
- (void).cxx_destruct;
- (void)applyConfirmedOptin:(_Bool)arg1;
- (void)showOptinConfirmationAlert:(id)arg1 optinChoice:(_Bool)arg2;
@property(readonly, nonatomic) double sidePadding;
- (void)updateLayout;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)selectedMoreOptions:(id)arg1;
- (void)selectedAboutDetail:(id)arg1;
- (void)selecedOptinChoice:(id)arg1;
- (id)imageResource;
- (id)moreOptionsButtonString;
- (id)aboutButtonString;
- (_Bool)legacyButtonStyles;
- (id)alternateButtonString;
- (id)suggestedButtonString;
- (id)detailString;
- (id)detailTitleString;
- (id)titleString;
- (id)init;

@end

