//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NRDevice, NSNumber, UIActivityIndicatorView, UIAlertView, UIBarButtonItem, UILabel, UIToolbar;

@interface COSPINComparisonViewController : UIViewController
{
    UILabel *_explanationLabel;
    UILabel *_pinCode;
    UIActivityIndicatorView *_spinnerView;
    UIToolbar *_toolbar;
    UIBarButtonItem *_pair;
    UIBarButtonItem *_cancel;
    NRDevice *_incomingDevice;
    NSNumber *_pinCodeValue;
    UIAlertView *_instructionAlert;
}

@property(retain, nonatomic) UIAlertView *instructionAlert; // @synthesize instructionAlert=_instructionAlert;
@property(retain, nonatomic) NSNumber *pinCodeValue; // @synthesize pinCodeValue=_pinCodeValue;
@property(retain, nonatomic) NRDevice *incomingDevice; // @synthesize incomingDevice=_incomingDevice;
@property(retain, nonatomic) UIBarButtonItem *cancel; // @synthesize cancel=_cancel;
@property(retain, nonatomic) UIBarButtonItem *pair; // @synthesize pair=_pair;
@property(retain, nonatomic) UIToolbar *toolbar; // @synthesize toolbar=_toolbar;
@property(retain, nonatomic) UIActivityIndicatorView *spinnerView; // @synthesize spinnerView=_spinnerView;
@property(retain, nonatomic) UILabel *pinCode; // @synthesize pinCode=_pinCode;
@property(retain, nonatomic) UILabel *explanationLabel; // @synthesize explanationLabel=_explanationLabel;
- (void).cxx_destruct;
- (void)_layoutSubViews;
- (void)cancel:(id)arg1;
- (void)pair:(id)arg1;
- (void)deviceDidBeginActivation:(id)arg1;
- (void)gotPinAndDevice:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)dealloc;
- (id)initWithDevice:(id)arg1;

@end

