//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class COSPasscodeViewController, NSString;

@protocol COSPasscodeViewControllerDelegate <NSObject>

@optional
- (_Bool)shouldShowCancelButtonForPasscodeViewController:(COSPasscodeViewController *)arg1;
- (_Bool)passcodeViewController:(COSPasscodeViewController *)arg1 passcodeIsCorrect:(NSString *)arg2;
- (void)passcodeViewController:(COSPasscodeViewController *)arg1 didFinishSettingUpPasscode:(NSString *)arg2;
- (void)passcodeViewController:(COSPasscodeViewController *)arg1 passcodeViewIsVisible:(_Bool)arg2;
- (void)passcodeViewController:(COSPasscodeViewController *)arg1 wasDismissedWithReason:(int)arg2;
@end

