//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIImageView;

@interface COSPhoneView : UIView
{
    long long _style;
    UIImageView *_deviceImageView;
    UIImageView *_screenImageView;
    NSString *_screenImageName;
}

@property(copy, nonatomic) NSString *screenImageName; // @synthesize screenImageName=_screenImageName;
- (void).cxx_destruct;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1;

@end

