//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DevicePINController.h"

#import "UINavigationControllerDelegate.h"
#import "UIPopoverControllerDelegatePrivate.h"

@class NSString, UINavigationController, UIPopoverController, UIStatusBar, UIView, UIViewController;

@interface COSPasscodeViewController : DevicePINController <UINavigationControllerDelegate, UIPopoverControllerDelegatePrivate>
{
    _Bool _passcodeViewVisible;
    id <COSPasscodeViewControllerDelegate> _delegate;
    UIPopoverController *_hostingPopoverController;
    NSString *_passcode;
    UIViewController *_presentorViewController;
    UINavigationController *_hostingNavigationController;
    UIStatusBar *_statusBar;
    UIView *_statusBarContainerView;
}

@property(retain, nonatomic) UIView *statusBarContainerView; // @synthesize statusBarContainerView=_statusBarContainerView;
@property(retain, nonatomic) UIStatusBar *statusBar; // @synthesize statusBar=_statusBar;
@property(retain, nonatomic) UINavigationController *hostingNavigationController; // @synthesize hostingNavigationController=_hostingNavigationController;
@property(retain, nonatomic) UIViewController *presentorViewController; // @synthesize presentorViewController=_presentorViewController;
@property(copy, nonatomic) NSString *passcode; // @synthesize passcode=_passcode;
@property(readonly, nonatomic) UIPopoverController *hostingPopoverController; // @synthesize hostingPopoverController=_hostingPopoverController;
@property(nonatomic, getter=isPasscodeViewVisible) _Bool passcodeViewVisible; // @synthesize passcodeViewVisible=_passcodeViewVisible;
@property(nonatomic) __weak id <COSPasscodeViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (unsigned long long)navigationControllerSupportedInterfaceOrientations:(id)arg1;
- (void)didAcceptSetPIN;
- (void)didAcceptEnteredPIN;
- (void)cancelButtonTapped;
- (void)_updateErrorTextAndFailureCount:(_Bool)arg1;
- (void)_slidePasscodeField;
- (void)setPane:(id)arg1;
- (void)setPIN:(id)arg1;
- (_Bool)pinIsAcceptable:(id)arg1 outError:(id *)arg2;
- (_Bool)validatePIN:(id)arg1;
- (_Bool)simplePIN;
- (_Bool)requiresKeyboard;
- (int)pinLength;
- (_Bool)useProgressiveDelays;
- (_Bool)switchFromKeypadToKeyboard;
- (id)stringsBundle;
- (_Bool)_shouldShowCancelButton;
- (void)_notifyDelegateOfPasscodeViewDismissalWithReason:(int)arg1;
- (void)_notifyDelegateOfPasscodeViewVisibilityChange;
- (void)_didFinishDismissingPasscodeViewWithReason:(int)arg1 notifyDelegate:(_Bool)arg2;
- (void)_dismissPasscodeViewAnimated:(_Bool)arg1 withReason:(int)arg2 notifyDelegate:(_Bool)arg3;
- (void)_presentPasscodeViewWithParentViewController:(id)arg1 animated:(_Bool)arg2;
- (void)dismissPasscodeViewAnimated:(_Bool)arg1 reason:(int)arg2;
- (void)presentPasscodeViewWithParentViewController:(id)arg1 animated:(_Bool)arg2;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewWillLayoutSubviews;
- (void)loadView;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

