//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PSListController.h"

@class NRDevice, NRPairedDeviceRegistry;

@interface COSPairingController : PSListController
{
    NRPairedDeviceRegistry *_nanoRegistry;
    NRDevice *_device;
}

@property(retain, nonatomic) NRDevice *device; // @synthesize device=_device;
@property(retain, nonatomic) NRPairedDeviceRegistry *nanoRegistry; // @synthesize nanoRegistry=_nanoRegistry;
- (void).cxx_destruct;
- (void)nanoRegistryStatusChanged:(id)arg1;
- (void)_applicationResumed:(id)arg1;
- (void)enableDisableUnpairButton:(unsigned long long)arg1;
- (void)confirmedUnpair;
- (void)confirmUnpairing;
- (id)specifiers;
- (void)dealloc;
- (id)init;

@end

