//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "COSOptinViewController.h"

@interface COSPasscodeAdvancedViewController : COSOptinViewController
{
}

- (void)removeFromNavHierarchyOf:(id)arg1;
- (void)selecedOptinChoice:(id)arg1;
- (_Bool)legacyButtonStyles;
- (id)alternateButtonString;
- (id)suggestedButtonString;
- (id)detailString;
- (id)detailTitleString;
- (id)imageResource;
- (id)titleString;
- (void)dealloc;
- (id)init;

@end

