//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "COSOptinViewController.h"

@class UIButton, UILabel;

@interface COSPasscodeChoiceViewController : COSOptinViewController
{
    UIButton *_acceptButton;
    UIButton *_declineButton;
    UILabel *_footerLabel;
}

+ (_Bool)controllerNeedsToRun;
@property(retain, nonatomic) UILabel *footerLabel; // @synthesize footerLabel=_footerLabel;
@property(retain, nonatomic) UIButton *declineButton; // @synthesize declineButton=_declineButton;
@property(retain, nonatomic) UIButton *acceptButton; // @synthesize acceptButton=_acceptButton;
- (void).cxx_destruct;
- (_Bool)legacyButtonStyles;
- (void)selectedMoreOptions:(id)arg1;
- (id)detailTitleString;
- (id)moreOptionsButtonString;
- (id)alternateButtonString;
- (id)suggestedButtonString;
- (void)selecedOptinChoice:(id)arg1;
- (id)imageResource;
- (id)detailString;
- (id)titleString;
- (void)viewDidLoad;
- (id)init;

@end

