//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PSListController.h"

@class NSSManager;

@interface COSResetController : PSListController
{
    NSSManager *_manager;
}

@property(retain, nonatomic) NSSManager *manager; // @synthesize manager=_manager;
- (void).cxx_destruct;
- (void)resetCalendarSyncState:(id)arg1;
- (void)resetContactsSyncState:(id)arg1;
- (void)resetSyncState:(id)arg1;
- (void)resetAppLayoutConfirmed:(id)arg1;
- (void)eraseSettingsAndContent:(id)arg1;
- (void)confirmationSpecifierConfirmed:(id)arg1;
- (id)specifiers;
- (id)init;

@end

