//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "COSBuddyController.h"

@class COSRestoreHeaderView, NSMutableArray, NSString, UIView;

@interface COSRestoreSelectionViewController : UITableViewController <COSBuddyController>
{
    id <COSBuddyControllerDelegate> _delegate;
    COSRestoreHeaderView *_headerView;
    NSMutableArray *_restoreInstances;
    UIView *_navBlackoutView;
}

@property(retain, nonatomic) UIView *navBlackoutView; // @synthesize navBlackoutView=_navBlackoutView;
@property(retain, nonatomic) NSMutableArray *restoreInstances; // @synthesize restoreInstances=_restoreInstances;
@property(retain, nonatomic) COSRestoreHeaderView *headerView; // @synthesize headerView=_headerView;
@property(nonatomic) __weak id <COSBuddyControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)viewWillAppear:(_Bool)arg1;
- (_Bool)controllerAllowsNavigatingBackTo;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

