//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "COSNavigationController.h"

@class COSSecurePairingViewController;

@interface COSSecurePairingFlowViewController : COSNavigationController
{
    _Bool _darkStyle;
    id <COSManualSecurePairingDelegate> _pairingDelegate;
    COSSecurePairingViewController *_securePairingController;
}

@property(nonatomic) _Bool darkStyle; // @synthesize darkStyle=_darkStyle;
@property(retain, nonatomic) COSSecurePairingViewController *securePairingController; // @synthesize securePairingController=_securePairingController;
@property(nonatomic) __weak id <COSManualSecurePairingDelegate> pairingDelegate; // @synthesize pairingDelegate=_pairingDelegate;
- (void).cxx_destruct;
- (void)controllerCancelled:(id)arg1;
- (_Bool)isOverCamera;
- (id)initOverCameraStyle:(_Bool)arg1;

@end

