//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BPSNotificationAppController.h"

@interface COSSampleApplicationListController : BPSNotificationAppController
{
}

- (id)localizedPaneTitle;
- (id)linkListSelection:(id)arg1;
- (void)setLinkListSelection:(id)arg1 specifier:(id)arg2;
- (id)awesomeFeatureEnabled:(id)arg1;
- (void)setAwesomeFeatureEnabled:(id)arg1 specifier:(id)arg2;
- (id)localizedMirroringDetailFooter;
- (id)applicationGroupSpecifiers;
- (id)applicationBundleIdentifier;

@end

