//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PSSoftwareUpdateAnimatedIcon.h"

@class NSString;

@interface COSSoftwareUpdateAnimatedIcon : PSSoftwareUpdateAnimatedIcon
{
    NSString *_outerGearImageName;
}

@property(retain, nonatomic) NSString *outerGearImageName; // @synthesize outerGearImageName=_outerGearImageName;
- (void).cxx_destruct;
- (id)outerGearView;
- (id)outerGearShadowView;
- (id)innerGearView;

@end

