//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PSAppListController.h"

#import "SPDeviceConnectionDelegate.h"

@class BPSAppGlanceManager, NSString, PSSpecifier;

@interface COSSockPuppetAppListController : PSAppListController <SPDeviceConnectionDelegate>
{
    BPSAppGlanceManager *_manager;
    PSSpecifier *_glanceSpecifier;
}

@property(retain, nonatomic) PSSpecifier *glanceSpecifier; // @synthesize glanceSpecifier=_glanceSpecifier;
@property(retain, nonatomic) BPSAppGlanceManager *manager; // @synthesize manager=_manager;
- (void).cxx_destruct;
- (void)launchTestFlight:(id)arg1;
- (void)updateInstallStateForApplication:(id)arg1 installState:(long long)arg2;
- (id)puppetAppShows:(id)arg1;
- (void)setPuppetAppShows:(id)arg1 specifier:(id)arg2;
- (void)_resetAfterSockPuppetResponseWithState:(long long)arg1;
- (id)systemPolicy;
- (void)refreshGlanceSpecifierEnableStateAndReloadSpecifier:(_Bool)arg1;
- (id)specifiers;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

