//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PSListController.h"

#import "DevicePINControllerDelegate.h"
#import "NRDevicePropertyObserver.h"
#import "SUBManagerDelegate.h"
#import "UITableViewDelegate.h"

@class NRDevice, NSDateComponentsFormatter, NSObject<OS_dispatch_source>, NSString, PSSoftwareUpdateTitleCell, PSSpecifier, SUBDescriptor, SUBDownload, SUBManager;

@interface COSSoftwareUpdateController : PSListController <DevicePINControllerDelegate, SUBManagerDelegate, UITableViewDelegate, NRDevicePropertyObserver>
{
    _Bool _isExpectingScanResult;
    _Bool _hasReceivedValidFirstScanResult;
    _Bool _didEnterDevicePasscode;
    _Bool _inSetupFlow;
    _Bool _hasUpdatedSuccessfully;
    SUBManager *_subManager;
    SUBDownload *_download;
    SUBDescriptor *_update;
    PSSpecifier *_titleGroup;
    PSSoftwareUpdateTitleCell *_titleCell;
    PSSpecifier *_installButtonGroup;
    PSSpecifier *_installButtonSpecifier;
    SEL _termsAcceptanceAction;
    NSDateComponentsFormatter *_durationFormatter;
    long long _subState;
    NSObject<OS_dispatch_source> *_hidingProgressBarSource;
    CDUnknownBlockType _devicePasscodeCompletion;
    NRDevice *_pairedDevice;
}

@property(nonatomic) _Bool hasUpdatedSuccessfully; // @synthesize hasUpdatedSuccessfully=_hasUpdatedSuccessfully;
@property(retain, nonatomic) NRDevice *pairedDevice; // @synthesize pairedDevice=_pairedDevice;
@property(nonatomic, getter=isInSetupFlow) _Bool inSetupFlow; // @synthesize inSetupFlow=_inSetupFlow;
@property(copy, nonatomic) CDUnknownBlockType devicePasscodeCompletion; // @synthesize devicePasscodeCompletion=_devicePasscodeCompletion;
@property(nonatomic) _Bool didEnterDevicePasscode; // @synthesize didEnterDevicePasscode=_didEnterDevicePasscode;
@property(nonatomic) _Bool hasReceivedValidFirstScanResult; // @synthesize hasReceivedValidFirstScanResult=_hasReceivedValidFirstScanResult;
@property(nonatomic) _Bool isExpectingScanResult; // @synthesize isExpectingScanResult=_isExpectingScanResult;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *hidingProgressBarSource; // @synthesize hidingProgressBarSource=_hidingProgressBarSource;
@property(nonatomic) long long subState; // @synthesize subState=_subState;
@property(retain, nonatomic) NSDateComponentsFormatter *durationFormatter; // @synthesize durationFormatter=_durationFormatter;
@property(nonatomic) SEL termsAcceptanceAction; // @synthesize termsAcceptanceAction=_termsAcceptanceAction;
@property(retain, nonatomic) PSSpecifier *installButtonSpecifier; // @synthesize installButtonSpecifier=_installButtonSpecifier;
@property(retain, nonatomic) PSSpecifier *installButtonGroup; // @synthesize installButtonGroup=_installButtonGroup;
@property(retain, nonatomic) PSSoftwareUpdateTitleCell *titleCell; // @synthesize titleCell=_titleCell;
@property(retain, nonatomic) PSSpecifier *titleGroup; // @synthesize titleGroup=_titleGroup;
@property(retain, nonatomic) SUBDescriptor *update; // @synthesize update=_update;
@property(retain, nonatomic) SUBDownload *download; // @synthesize download=_download;
@property(retain, nonatomic) SUBManager *subManager; // @synthesize subManager=_subManager;
- (void).cxx_destruct;
- (void)handleInstallationError:(id)arg1;
- (void)handleDownloadError:(id)arg1;
- (void)handleScanError:(id)arg1;
- (void)handleManagerStateError:(id)arg1;
- (void)presentAlertForDuetDenialCondition:(unsigned long long)arg1;
- (void)_manager:(id)arg1 didFinishInstallation:(id)arg2;
- (void)manager:(id)arg1 didFinishInstallation:(id)arg2;
- (void)_manager:(id)arg1 didFailInstallation:(id)arg2 withError:(id)arg3;
- (void)manager:(id)arg1 didFailInstallation:(id)arg2 withError:(id)arg3;
- (void)_manager:(id)arg1 installationOfUpdate:(id)arg2 canProceed:(_Bool)arg3;
- (void)manager:(id)arg1 installationOfUpdate:(id)arg2 canProceed:(_Bool)arg3;
- (void)_manager:(id)arg1 willProceedWithInstallation:(id)arg2;
- (void)manager:(id)arg1 willProceedWithInstallation:(id)arg2;
- (void)_manager:(id)arg1 didFinishDownload:(id)arg2 willProceedWithInstallation:(_Bool)arg3 waitingForAdmissionControl:(_Bool)arg4;
- (void)manager:(id)arg1 didFinishDownload:(id)arg2 willProceedWithInstallation:(_Bool)arg3 waitingForAdmissionControl:(_Bool)arg4;
- (void)_manager:(id)arg1 didFailDownload:(id)arg2 withError:(id)arg3;
- (void)manager:(id)arg1 didFailDownload:(id)arg2 withError:(id)arg3;
- (void)_manager:(id)arg1 didChangeProgressOnDownload:(id)arg2;
- (void)manager:(id)arg1 didChangeProgressOnDownload:(id)arg2;
- (void)_manager:(id)arg1 scanRequestDidLocateUpdate:(id)arg2 error:(id)arg3;
- (void)manager:(id)arg1 scanRequestDidLocateUpdate:(id)arg2 error:(id)arg3;
- (void)devicePINControllerDidDismissPINPane:(id)arg1;
- (void)didAcceptEnteredPIN:(id)arg1;
- (id)controllerForSpecifier:(id)arg1;
- (void)detailedReleaseNotesDonePressed:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)specifiers;
- (_Bool)shouldReloadSpecifiersOnResume;
- (Class)tableViewClass;
- (void)willEnterForeground;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (void)presentViewController:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_reallyInstall;
- (void)install:(id)arg1;
- (void)scanForUpdatesInBackgound:(_Bool)arg1;
- (void)downloadTermsAccepted;
- (void)_termsDisagree;
- (void)_termsAgree;
- (void)presentPasscodePromptWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)presentPasscodePromptIfNecessaryWithHandler:(CDUnknownBlockType)arg1;
- (void)presentTermsIfNecessaryWithAcceptanceAction:(SEL)arg1;
- (void)downloadAndInstall:(id)arg1;
- (void)displayInstallButtonSpinner:(_Bool)arg1 reloadSpecifier:(_Bool)arg2;
- (void)resetInstallButtonEnabledStateAndReloadSpecifier:(_Bool)arg1;
- (void)cancelHidingProgressBarAfterDelay;
- (void)hideProgressBarAfterDelay;
- (void)updateTableViewWithTask:(CDUnknownBlockType)arg1;
- (void)transitionToState:(long long)arg1;
- (id)specifiersForState:(long long)arg1;
- (_Bool)shouldShowTableViewForState:(long long)arg1;
- (void)handleManagerState:(long long)arg1 update:(id)arg2 error:(id)arg3;
- (void)queryManagerState;
- (void)device:(id)arg1 propertyDidChange:(id)arg2 fromValue:(id)arg3;
- (void)startCallingIntoSUB;
- (void)finishedActivating;
- (void)startActivatingIfNeeded;
- (void)enteredCompatibilityState:(id)arg1;
- (void)cancelUpdateInSetupPressed;
- (void)presentWithController:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

