//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface COSSetupFlowPreferences : NSObject
{
}

+ (unsigned long long)position;
+ (void)beganController:(unsigned long long)arg1;

@end

