//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "COSPreferencesListController.h"

@class NSDictionary, NSMutableDictionary, UIViewController;

@interface COSSettingsListController : COSPreferencesListController
{
    NSDictionary *_inheritedWhiteList;
    UIViewController *_nothingSelectedController;
    NSMutableDictionary *_sockPuppetAppMapping;
}

+ (id)sharedTopLevelIconsLazyLoadingQueue;
@property(retain, nonatomic) NSMutableDictionary *sockPuppetAppMapping; // @synthesize sockPuppetAppMapping=_sockPuppetAppMapping;
@property(retain, nonatomic) UIViewController *nothingSelectedController; // @synthesize nothingSelectedController=_nothingSelectedController;
@property(retain, nonatomic) NSDictionary *inheritedWhiteList; // @synthesize inheritedWhiteList=_inheritedWhiteList;
- (void).cxx_destruct;
- (id)localizedPrefsStringForString:(id)arg1;
- (id)additionalSpecifiers;
- (id)sockPuppetAppValue:(id)arg1;
- (id)sockPuppetApps;
- (id)hardcodedSpecifiers;
- (void)reloadSpecifiers;
- (_Bool)reloadsWhenBecomingActive;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)indexOfGeneralController;
- (id)generalViewController;
- (void)viewWillAppear:(_Bool)arg1;
- (id)specifiers;
- (id)settingsFileName;
- (id)title;
- (void)dealloc;
- (id)init;

@end

