//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BuddyTCSubControllerDelegate.h"
#import "COSBuddyController.h"
#import "RUILoaderDelegate.h"
#import "RUIObjectModelDelegate.h"

@class BuddySimpleTCController, NSData, NSMutableArray, NSString, RUILoader, RUIObjectModel, RUIPage, UIAlertView, UIViewController;

@interface COSTermsConditionsController : NSObject <COSBuddyController, BuddyTCSubControllerDelegate, RUILoaderDelegate, RUIObjectModelDelegate>
{
    RUIObjectModel *_objectModel;
    UIAlertView *_tcConfirmationAlert;
    _Bool _warrantySentinelExists;
    id <COSBuddyControllerDelegate> _delegate;
    NSData *_onlineTerms;
    RUILoader *_loader;
    RUIPage *_loadingPage;
    NSMutableArray *_objectModels;
    UIViewController *_viewController;
    NSData *_offlineLicense;
    NSData *_offlineMultiterms;
    NSData *_offlineWarranty;
    BuddySimpleTCController *_offlineLicenseVC;
    BuddySimpleTCController *_offlineWarrantyVC;
}

+ (_Bool)controllerNeedsToRun;
@property(retain, nonatomic) BuddySimpleTCController *offlineWarrantyVC; // @synthesize offlineWarrantyVC=_offlineWarrantyVC;
@property(retain, nonatomic) BuddySimpleTCController *offlineLicenseVC; // @synthesize offlineLicenseVC=_offlineLicenseVC;
@property(retain, nonatomic) NSData *offlineWarranty; // @synthesize offlineWarranty=_offlineWarranty;
@property(retain, nonatomic) NSData *offlineMultiterms; // @synthesize offlineMultiterms=_offlineMultiterms;
@property(retain, nonatomic) NSData *offlineLicense; // @synthesize offlineLicense=_offlineLicense;
@property(retain, nonatomic) UIViewController *viewController; // @synthesize viewController=_viewController;
@property(retain, nonatomic) NSMutableArray *objectModels; // @synthesize objectModels=_objectModels;
@property(retain, nonatomic) RUIPage *loadingPage; // @synthesize loadingPage=_loadingPage;
@property(retain, nonatomic) RUILoader *loader; // @synthesize loader=_loader;
@property(retain, nonatomic) NSData *onlineTerms; // @synthesize onlineTerms=_onlineTerms;
@property(nonatomic) _Bool warrantySentinelExists; // @synthesize warrantySentinelExists=_warrantySentinelExists;
@property(nonatomic) __weak id <COSBuddyControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)buddyTCSubController:(id)arg1 didFinishWithAgree:(_Bool)arg2;
- (void)objectModel:(id)arg1 didNavigateBackFromController:(id)arg2 withGesture:(_Bool)arg3;
- (void)objectModel:(id)arg1 pressedLink:(id)arg2 httpMethod:(id)arg3;
- (void)objectModel:(id)arg1 pressedButton:(id)arg2 attributes:(id)arg3;
- (id)parentViewControllerForObjectModel:(id)arg1;
- (void)_popObjectModelAnimated:(_Bool)arg1;
- (void)_cleanupLoader;
- (void)loader:(id)arg1 didFailWithError:(id)arg2;
- (void)loader:(id)arg1 receivedObjectModel:(id)arg2 actionSignal:(int)arg3;
- (_Bool)holdBeforeDisplaying;
- (void)queryGizmoForShowWarrantySentinel;
- (void)enteredCompatibilityState:(id)arg1;
- (void)removeFromNavHierarchyOf:(id)arg1;
- (id)_navigationController;
- (void)retrieveOfflineTerms;
- (void)handleOnlineTermsAndConditionsResponse:(id)arg1 error:(id)arg2;
- (void)requestOnlineTermsAndConditions;
- (id)offlineWarrantyController;
- (id)offlineLicenseController;
- (void)offlineTermsResponse:(id)arg1;
- (void)warrantySentinelResponse:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

