//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PSListController.h"

@class NSSManager;

@interface COSUsageBundleDetailController : PSListController
{
    NSSManager *_nssManager;
}

@property(retain, nonatomic) NSSManager *nssManager; // @synthesize nssManager=_nssManager;
- (void).cxx_destruct;
- (void)delete;
- (void)confirmDeletion;
- (id)valueForSpecifier:(id)arg1;
- (id)specifiers;
- (id)usageBundle;

@end

