//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "PSHeaderFooterView.h"

@class UILabel;

@interface COSUsageTotalUsedHeader : UIView <PSHeaderFooterView>
{
    UILabel *_usedLabel;
    UILabel *_availableLabel;
    UILabel *_titleLabel;
    double _height;
}

@property(nonatomic) double height; // @synthesize height=_height;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UILabel *availableLabel; // @synthesize availableLabel=_availableLabel;
@property(retain, nonatomic) UILabel *usedLabel; // @synthesize usedLabel=_usedLabel;
- (void).cxx_destruct;
- (double)preferredHeightForWidth:(double)arg1;
- (void)layoutSubviews;
- (void)setUsed:(id)arg1;
- (void)setAvailable:(id)arg1;
- (void)setName:(id)arg1;
- (void)recalcHeight;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithSpecifier:(id)arg1;

@end

