//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NCContentViewController.h"

@class NSString, UIImageView, UILabel;

@interface CKAudioDescriptionViewController : NCContentViewController
{
    _Bool _showsRecordingText;
    UILabel *_timeLabel;
    NSString *_timeFormat;
    double _duration;
    UIImageView *_imageView;
    UILabel *_statusLabel;
}

+ (_Bool)_isSecureForRemoteViewService;
@property(nonatomic) _Bool showsRecordingText; // @synthesize showsRecordingText=_showsRecordingText;
@property(retain, nonatomic) UILabel *statusLabel; // @synthesize statusLabel=_statusLabel;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(nonatomic) double duration; // @synthesize duration=_duration;
@property(copy, nonatomic) NSString *timeFormat; // @synthesize timeFormat=_timeFormat;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
- (void)_hideRecordingText:(id)arg1;
- (void)_showRecordingText:(id)arg1;
- (void)_showExpiresText:(id)arg1;
- (void)updateTimeStringWithTime:(double)arg1;
- (void)viewDidLayoutSubviews;
- (void)setContext:(id)arg1;
- (void)viewDidLoad;
- (_Bool)_disableAutomaticKeyboardBehavior;
- (void)dealloc;
- (id)init;

@end

