//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NCBannerAccessoryViewController.h"

#import "CKAudioControllerDelegate.h"

@class CKAudioController, CKAudioMediaObject, CKAudioProgressView, NSString;

@interface CKBannerPlaybackViewController : NCBannerAccessoryViewController <CKAudioControllerDelegate>
{
    CKAudioMediaObject *_mediaObject;
    CKAudioProgressView *_progressView;
    CKAudioController *_audioController;
    double _duration;
    double _currentProgress;
    double _lastProgress;
}

+ (_Bool)_isSecureForRemoteViewService;
@property(nonatomic) double lastProgress; // @synthesize lastProgress=_lastProgress;
@property(nonatomic) double currentProgress; // @synthesize currentProgress=_currentProgress;
@property(nonatomic) double duration; // @synthesize duration=_duration;
@property(retain, nonatomic) CKAudioController *audioController; // @synthesize audioController=_audioController;
@property(retain, nonatomic) CKAudioProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) CKAudioMediaObject *mediaObject; // @synthesize mediaObject=_mediaObject;
- (void)didStop:(id)arg1;
- (void)didFinish:(id)arg1;
- (void)didPause:(id)arg1;
- (void)_updateTime:(id)arg1;
- (void)audioControllerDidStop:(id)arg1;
- (void)audioControllerDidPause:(id)arg1;
- (void)audioController:(id)arg1 mediaObjectProgressDidChange:(id)arg2 currentTime:(double)arg3 duration:(double)arg4;
- (void)audioController:(id)arg1 mediaObjectDidFinishPlaying:(id)arg2;
- (void)tapGestureRecognized:(id)arg1;
- (struct CGSize)preferredContentSize;
- (void)viewDidLayoutSubviews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)dismiss;
- (void)setContext:(id)arg1;
- (void)viewDidLoad;
- (_Bool)_disableAutomaticKeyboardBehavior;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

