//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CKAudioControllerDelegate.h"

@class CKAudioController, NSMutableArray, NSMutableDictionary, NSString;

@interface CKInlineReplyRaiseController : NSObject <CKAudioControllerDelegate>
{
    _Bool _raiseToListen;
    _Bool _allowRaiseToReply;
    _Bool _isRaiseToReply;
    id <CKInlineReplyRaiseControllerDelegate> _delegate;
    CKAudioController *_audioController;
    NSMutableDictionary *_playingAudioMessageGUIDs;
    NSMutableArray *_playedMediaObjects;
}

@property(nonatomic) _Bool isRaiseToReply; // @synthesize isRaiseToReply=_isRaiseToReply;
@property(nonatomic) _Bool allowRaiseToReply; // @synthesize allowRaiseToReply=_allowRaiseToReply;
@property(nonatomic, getter=isRaiseToListen) _Bool raiseToListen; // @synthesize raiseToListen=_raiseToListen;
@property(retain, nonatomic) NSMutableArray *playedMediaObjects; // @synthesize playedMediaObjects=_playedMediaObjects;
@property(retain, nonatomic) NSMutableDictionary *playingAudioMessageGUIDs; // @synthesize playingAudioMessageGUIDs=_playingAudioMessageGUIDs;
@property(retain, nonatomic) CKAudioController *audioController; // @synthesize audioController=_audioController;
@property(nonatomic) id <CKInlineReplyRaiseControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)audioController:(id)arg1 mediaObjectProgressDidChange:(id)arg2 currentTime:(double)arg3 duration:(double)arg4;
- (void)audioControllerDidStop:(id)arg1;
- (void)audioControllerDidPause:(id)arg1;
- (void)audioController:(id)arg1 mediaObjectDidFinishPlaying:(id)arg2;
- (void)messageEntryViewRecordingDidChange:(id)arg1;
- (void)dismissBulletins;
- (id)unplayedAudioMessageMediaObjectsForChatGUID:(id)arg1;
- (void)send;
- (void)handleActionIdentifier:(id)arg1;
- (void)proximityStateDidChange:(_Bool)arg1;
- (void)startPlaybackForChatGUID:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

