//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SPAppUsageTrack : NSObject
{
    unsigned int toGizmo[13];
    unsigned int toComp[13];
}

- (unsigned int *)toCompArray;
- (unsigned int *)toGizmoArray;
- (void)incToComp:(int)arg1;
- (void)incToGizmo:(int)arg1;
- (id)init;

@end

