//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue>;

@interface SPCompanionAppInstaller : NSObject
{
    NSMutableDictionary *_applicationInstallations;
    NSObject<OS_dispatch_queue> *_installer_queue;
}

+ (unsigned long long)chunkCountForFileAtPath:(id)arg1;
+ (id)sharedInstance;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *installer_queue; // @synthesize installer_queue=_installer_queue;
@property(retain) NSMutableDictionary *applicationInstallations; // @synthesize applicationInstallations=_applicationInstallations;
- (void).cxx_destruct;
- (void)deletePathStateFile;
- (void)createPathStateFile;
- (void)removeInstallationEntryForApplicationWithIdentifier:(id)arg1;
- (_Bool)isInstallationInProgressForApplicationWithIdentifier:(id)arg1;
- (void)cancelPendingInstallations;
- (void)installAllApplicationsForProcessWithIdentifier:(id)arg1;
- (void)cancelInstallationIfNeeded:(id)arg1;
- (void)removeApplicationWithBundleIDActual:(id)arg1 installer:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)removeApplicationWithBundleID:(id)arg1 installer:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)removeApplicationWithIdentifier:(id)arg1 installer:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (_Bool)removeApplicationOnSimulatorWithIdentifier:(id)arg1;
- (_Bool)installApplicationOnSimulatorWithIdentifier:(id)arg1 applicationName:(id)arg2 bomPath:(id)arg3 error:(id *)arg4;
- (void)sendInstallationDataWithPath:(id)arg1 dataType:(id)arg2 name:(id)arg3 info:(id)arg4 installer:(id)arg5 completion:(CDUnknownBlockType)arg6;
- (void)sendApplicationIconsWithInfo:(id)arg1 installer:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)installApplicationWithIdentifierActual:(id)arg1 installer:(id)arg2 idsPriority:(long long)arg3 completion:(CDUnknownBlockType)arg4;
- (void)installApplicationWithIdentifier:(id)arg1 installer:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)installApplicationWithIdentifier:(id)arg1 installer:(id)arg2 idsPriority:(long long)arg3 completion:(CDUnknownBlockType)arg4;
- (id)init;

@end

