//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPRemoteInterfaceProtocol.h"

@class NSString;

@interface SPCompanionAppServerProtocolStub : NSObject <SPRemoteInterfaceProtocol>
{
}

- (void)dataInterfaceWillResignActive:(id)arg1;
- (void)dataInterfaceDidBecomeActive:(id)arg1;
- (void)applicationIsStillActive;
- (void)applicationWillResignActive:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationDidFinishConnecting:(id)arg1;
- (void)applicationContentsDidReset:(id)arg1;
- (void)applicationDidTerminate:(id)arg1;
- (void)receiveProtoData:(id)arg1 fromIdentifier:(id)arg2;
- (void)receiveData:(id)arg1 fromIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

