//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BLTPingSubscriber, NSMutableDictionary, NSObject<OS_dispatch_queue>;

@interface SPCompanionNotificationHandler : NSObject
{
    NSMutableDictionary *_serializedContextsByNotificationID;
    NSObject<OS_dispatch_queue> *_notificationContextsAccessQueue;
    BLTPingSubscriber *_pingSubscriber;
    _Bool _hasSubscribedWithMachServiceName;
    _Bool _contextSaveIsPending;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)storeNotificationContext:(id)arg1 forNotificationID:(id)arg2;
- (id)contextForNotificationID:(id)arg1;
- (id)init;
- (void)updateSubscriptionsWithGizmoPersistentDomain:(id)arg1;
- (void)_storeBulletin:(id)arg1;
- (id)_restoredNotificationContexts;
- (void)_saveNotificationContextsSoon;
- (id)notificationContextsPlistURL;
- (void)_startExpiringNotificationsWithDelay:(double)arg1;
- (void)_startNotificationExpirationActivity;
- (void)_startNotificationExpirationTimerWithDelay:(double)arg1;
- (void)_removeExpiredNotificationsWithCompletionHandler:(CDUnknownBlockType)arg1;

@end

