//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SPSecurity : NSObject
{
}

+ (void)validateWatchKitApplicationInfoDictionary:(id)arg1 error:(id *)arg2;
+ (void)validateApplicationName:(id)arg1 error:(id *)arg2;
+ (void)validateGizmoApplicationSignature:(id)arg1 error:(id *)arg2;
+ (void)validateApplicationWithUrl:(id)arg1 error:(id *)arg2;
+ (void)validateExtensionWithUrl:(id)arg1 error:(id *)arg2;

@end

