//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@interface ANCAlert : NSObject <NSCopying>
{
    unsigned char _categoryID;
}

@property(readonly, nonatomic) unsigned char categoryID; // @synthesize categoryID=_categoryID;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)hasExtraContent;
- (_Bool)performNegativeAction;
- (_Bool)performPositiveAction;
- (id)negativeActionLabel;
- (id)positiveActionLabel;
- (_Bool)hasNegativeAction;
- (_Bool)hasPositiveAction;
- (id)date;
- (id)message;
- (id)subtitle;
- (id)title;
- (id)appIdentifier;
- (_Bool)isImportant;
- (id)initWithCategoryID:(unsigned char)arg1;

@end

