//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BBObserverDelegate.h"

@class BBObserver, CHManager, NSDictionary, NSMapTable, NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString;

@interface ANCAlertSource : NSObject <BBObserverDelegate>
{
    id <ANCAlertSourceDelegate> _delegate;
    NSObject<OS_dispatch_queue> *_queue;
    NSDictionary *_1stPartyAppIdentifierToCategoryMap;
    void *_addressBook;
    NSMutableDictionary *_alerts;
    NSMutableDictionary *_appIdentifierToCategoryCache;
    _Bool _bbDoNotDisturb;
    NSMutableDictionary *_bbBulletinAlerts;
    BBObserver *_bbObserver;
    NSMutableArray *_ctRingingCalls;
    NSMapTable *_ctIncomingCallAlerts;
    NSMutableArray *_chUnreadMissedCalls;
    NSMutableDictionary *_chMissedCallAlerts;
    CHManager *_chManager;
    NSMutableArray *_vvUnreadVoicemails;
    NSMapTable *_vvVoicemailAlerts;
}

- (unsigned char)categoryIDForGenreID:(unsigned long long)arg1;
- (unsigned long long)genreIDForGenre:(id)arg1;
- (void)combineCurrentArray:(id)arg1 withNewArray:(id)arg2 maxCount:(unsigned long long)arg3 objectRemoved:(CDUnknownBlockType)arg4 objectAdded:(CDUnknownBlockType)arg5;
- (void)addressBookChanged;
- (void)unreadVoicemailsChanged:(_Bool)arg1;
- (void)unreadVoicemailsChangedNotification;
- (void)callHistoryChanged:(_Bool)arg1;
- (void)callHistoryChangedNotification;
- (void)callIdentificationChanged:(id)arg1;
- (void)callStatusChanged;
- (unsigned char)categoryIDForAppIdentifier:(id)arg1;
- (_Bool)isSpecialSectionID:(id)arg1;
- (void)observer:(id)arg1 noteInvalidatedBulletinIDs:(id)arg2;
- (void)observer:(id)arg1 noteAlertBehaviorOverrideStateChanged:(unsigned long long)arg2;
- (void)observer:(id)arg1 removeBulletin:(id)arg2 forFeed:(unsigned long long)arg3;
- (void)observer:(id)arg1 modifyBulletin:(id)arg2 forFeed:(unsigned long long)arg3;
- (void)observer:(id)arg1 addBulletin:(id)arg2 forFeed:(unsigned long long)arg3;
- (void)removeAlert:(id)arg1;
- (void)modifyAlert:(id)arg1;
- (void)addAlert:(id)arg1 isPreExisting:(_Bool)arg2;
- (void)dealloc;
- (id)displayNameForAppIdentifier:(id)arg1;
- (id)alertsForCategoryID:(unsigned char)arg1;
- (void)invalidate;
- (id)initWithDelegate:(id)arg1 queue:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

