//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ANCAlert.h"

@class BBBulletin, BBObserver;

@interface ANCBulletinAlert : ANCAlert
{
    BBBulletin *_bulletin;
    BBObserver *_observer;
}

@property(retain, nonatomic) BBBulletin *bulletin; // @synthesize bulletin=_bulletin;
- (_Bool)hasExtraContent;
- (_Bool)performNegativeAction;
- (id)negativeActionLabel;
- (_Bool)hasNegativeAction;
- (id)date;
- (id)message;
- (id)subtitle;
- (id)title;
- (id)appIdentifier;
- (void)dealloc;
- (id)initWithBulletin:(id)arg1 observer:(id)arg2 categoryID:(unsigned char)arg3;

@end

