//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ANCAlert;

@interface ANCNotification : NSObject
{
    unsigned int _UID;
    ANCAlert *_alert;
    _Bool _isDirty;
}

@property(nonatomic) _Bool isDirty; // @synthesize isDirty=_isDirty;
@property(readonly, nonatomic) ANCAlert *alert; // @synthesize alert=_alert;
@property(readonly, nonatomic) unsigned int UID; // @synthesize UID=_UID;
- (void)dealloc;
- (id)initWithUID:(unsigned int)arg1 alert:(id)arg2;

@end

