//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ServerService.h"

#import "ANCAlertSourceDelegate.h"

@class ANCAlertSource, CBMutableCharacteristic, NSMutableDictionary, NSMutableSet, NSObject<OS_dispatch_queue>, NSString;

@interface ANCService : ServerService <ANCAlertSourceDelegate>
{
    CBMutableCharacteristic *_controlPoint;
    CBMutableCharacteristic *_notificationSource;
    CBMutableCharacteristic *_dataSource;
    NSObject<OS_dispatch_queue> *_queue;
    NSMutableSet *_activeCentrals;
    unsigned int _uidGenerator;
    NSMutableDictionary *_uidMap;
    NSMutableDictionary *_alertMap;
    ANCAlertSource *_alertSource;
}

@property(retain, nonatomic) ANCAlertSource *alertSource; // @synthesize alertSource=_alertSource;
@property(retain, nonatomic) NSMutableDictionary *alertMap; // @synthesize alertMap=_alertMap;
@property(retain, nonatomic) NSMutableDictionary *uidMap; // @synthesize uidMap=_uidMap;
@property(retain, nonatomic) NSMutableSet *activeCentrals; // @synthesize activeCentrals=_activeCentrals;
- (id)appAttributeIDToString:(unsigned char)arg1;
- (id)notificationAttributeIDToString:(unsigned char)arg1;
- (id)eventFlagsToString:(unsigned char)arg1;
- (id)categoryIDToString:(unsigned char)arg1;
- (id)eventIDToString:(unsigned char)arg1;
- (id)invocationForUpdateDataSource:(id)arg1 central:(id)arg2;
- (id)responseForAppAttributeID:(unsigned char)arg1 appIdentifier:(id)arg2;
- (id)responseForNotificationAttributeID:(unsigned char)arg1 maxLength:(unsigned short)arg2 notification:(id)arg3;
- (id)responseForAttributeID:(unsigned char)arg1 maxLength:(unsigned short)arg2 attribute:(id)arg3;
- (id)notificationForAlert:(id)arg1;
- (id)notificationForUID:(unsigned int)arg1;
- (void)alertRemoved:(id)arg1 isSilent:(_Bool)arg2;
- (void)alertModified:(id)arg1 isSilent:(_Bool)arg2;
- (void)alertAdded:(id)arg1 isSilent:(_Bool)arg2 isPreExisting:(_Bool)arg3;
- (void)peripheralManager:(id)arg1 central:(id)arg2 didUnsubscribeFromCharacteristic:(id)arg3;
- (void)peripheralManager:(id)arg1 central:(id)arg2 didSubscribeToCharacteristic:(id)arg3;
- (void)peripheralManager:(id)arg1 didReceiveWriteRequests:(id)arg2;
- (void)stopNotifications;
- (void)startNotifications;
- (void)updateDataSource:(id)arg1 central:(id)arg2;
- (void)updateNotificationSource:(unsigned char)arg1 notification:(id)arg2 sourceFlags:(unsigned char)arg3 centrals:(id)arg4;
- (void)updateNotificationSource:(unsigned char)arg1 notification:(id)arg2 sourceFlags:(unsigned char)arg3;
- (long long)handlePerformNotificationActionCommand:(id)arg1;
- (long long)handleGetAppAttributesCommand:(id)arg1;
- (long long)handleGetNotificationAttributesCommand:(id)arg1;
- (long long)handleControlPointWrite:(id)arg1;
- (void)handleWriteRequests:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

