//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ANCAlert.h"

@class VMVoicemail;

@interface ANCVoicemailAlert : ANCAlert
{
    VMVoicemail *_voicemail;
    void *_addressBook;
}

- (_Bool)performNegativeAction;
- (_Bool)performPositiveAction;
- (id)negativeActionLabel;
- (id)positiveActionLabel;
- (_Bool)hasNegativeAction;
- (_Bool)hasPositiveAction;
- (id)date;
- (id)message;
- (id)subtitle;
- (id)title;
- (id)appIdentifier;
- (void)dealloc;
- (id)initWithVoicemail:(id)arg1 addressBook:(void *)arg2;

@end

