//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CBMutableCharacteristic, NSArray, NSData;

@interface ATTUpdate : NSObject
{
    NSData *_value;
    CBMutableCharacteristic *_characteristic;
    NSArray *_centrals;
}

+ (id)updateWithValue:(id)arg1 characteristic:(id)arg2 centrals:(id)arg3;
@property(readonly, nonatomic) NSArray *centrals; // @synthesize centrals=_centrals;
@property(readonly, nonatomic) CBMutableCharacteristic *characteristic; // @synthesize characteristic=_characteristic;
@property(readonly, nonatomic) NSData *value; // @synthesize value=_value;
- (void)dealloc;
- (id)initWithValue:(id)arg1 characteristic:(id)arg2 centrals:(id)arg3;

@end

