//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ClientService.h"

@class CBCharacteristic, NSTimer;

@interface AuthenticationService : ClientService
{
    CBCharacteristic *_versionCharacteristic;
    CBCharacteristic *_certificate1Characteristic;
    CBCharacteristic *_certificate2Characteristic;
    CBCharacteristic *_challengeResponseCharacteristic;
    long long _authState;
    struct __CFDictionary *_authInfo;
    NSTimer *_authTimer;
}

+ (void)initialize;
+ (id)UUID;
- (id)authStateString;
- (void)authenticationDidFail;
- (void)authenticationDidSucceed;
- (_Bool)verifyCertificateIsUnique;
- (id)certificateSerialNumber;
- (void)peripheral:(id)arg1 didUpdateNotificationStateForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didWriteValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didUpdateValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didDiscoverCharacteristicsForService:(id)arg2 error:(id)arg3;
- (void)authTimeout;
- (void)verifyChallenge;
- (void)issueChallenge;
- (void)dealloc;
- (void)stop;
- (void)start;
- (id)initWithManager:(id)arg1 peripheral:(id)arg2 service:(id)arg3;

@end

