//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ClientService.h"

@class CBCharacteristic;

@interface BatteryClientService : ClientService
{
    CBCharacteristic *_batteryLevel;
    CBCharacteristic *_batteryPowerState;
}

+ (id)UUID;
- (id)batteryPowerStateString:(unsigned char)arg1;
- (void)extractBatteryPowerState;
- (void)extractBatteryLevel;
- (void)peripheral:(id)arg1 didUpdateNotificationStateForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didUpdateValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didDiscoverCharacteristicsForService:(id)arg2 error:(id)arg3;
- (void)dealloc;
- (void)start;
- (id)initWithManager:(id)arg1 peripheral:(id)arg2 service:(id)arg3;

@end

