//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BTLEXpcConnection, NSObject<OS_xpc_object>;

@interface BTLEXpcServer : NSObject
{
    NSObject<OS_xpc_object> *_xpcServer;
    BTLEXpcConnection *_serverConnection;
}

+ (id)instance;
- (void)handleXpcDisconnection:(id)arg1;
- (void)handleConnection:(id)arg1;
- (void)handleEvent:(id)arg1;
- (id)init;
- (void)sendSetConnectionParametersMsg:(id)arg1 forPeer:(id)arg2;
- (void)sendEnableBTSyncMsg:(unsigned short)arg1 forPeer:(id)arg2;
- (void)sendDisconnectClassicDeviceMsg:(id)arg1;

@end

