//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CBPeripheralDelegate.h"

@class CBPeripheral, NSMapTable, NSMutableSet, NSString;

@interface ClientServiceManager : NSObject <CBPeripheralDelegate>
{
    CBPeripheral *_peripheral;
    NSMapTable *_clientServiceMap;
    unsigned long long _startPriority;
    NSMutableSet *_startingClientServices;
}

+ (void)initialize;
- (void)peripheral:(id)arg1 didUpdateValueForDescriptor:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didDiscoverDescriptorsForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didUpdateNotificationStateForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didWriteValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didUpdateValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didDiscoverCharacteristicsForService:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didDiscoverServices:(id)arg2;
- (void)peripheral:(id)arg1 didModifyServices:(id)arg2;
- (void)analyzeError:(id)arg1;
- (void)startClientServices;
- (void)dealloc;
- (void)clientService:(id)arg1 desiresConnectionParameters:(id)arg2;
- (void)clientServiceDidStart:(id)arg1;
- (id)clientServiceForUUID:(id)arg1;
- (id)initWithPeripheral:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

