//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CBPeripheralDelegate.h"

@class CBPeripheral, CBService, ClientServiceManager, NSString, NSTimer;

@interface ClientService : NSObject <CBPeripheralDelegate>
{
    ClientServiceManager *_manager;
    CBPeripheral *_peripheral;
    CBService *_service;
    _Bool _isPrimary;
    unsigned long long _priority;
    double _startTimeout;
    _Bool _isStarted;
    NSTimer *_startTimer;
}

+ (id)UUID;
@property(readonly, nonatomic) _Bool isStarted; // @synthesize isStarted=_isStarted;
@property(readonly, nonatomic) unsigned long long priority; // @synthesize priority=_priority;
@property(readonly, nonatomic) _Bool isPrimary; // @synthesize isPrimary=_isPrimary;
- (void)startTimeout;
- (void)dealloc;
- (void)notifyDidStart;
- (id)initWithManager:(id)arg1 peripheral:(id)arg2 service:(id)arg3;
- (void)stop;
- (void)start;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

