//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CBCentralManagerDelegate.h"

@class CBCentralManager, NSArray, NSMutableDictionary, NSMutableSet, NSString, TransactionAssertion;

@interface ConnectionManager : NSObject <CBCentralManagerDelegate>
{
    CBCentralManager *_centralManager;
    NSMutableDictionary *_connectOnceIdentifiersMap;
    NSMutableDictionary *_connectAlwaysIdentifiersMap;
    NSMutableSet *_blacklistedIdentifiers;
    TransactionAssertion *_connectionAssertion;
    NSArray *_peripherals;
    NSMutableDictionary *_clientServiceManagerMap;
}

+ (id)instance;
@property(retain, nonatomic) NSArray *peripherals; // @synthesize peripherals=_peripherals;
@property(retain, nonatomic) NSMutableDictionary *connectAlwaysIdentifiersMap; // @synthesize connectAlwaysIdentifiersMap=_connectAlwaysIdentifiersMap;
- (id)centralManagerStateString;
- (void)peerIsUsingBuiltinService:(id)arg1;
- (void)authDidFail:(id)arg1;
- (void)authDidSucceed:(id)arg1;
- (void)peripheralPairingDidFail:(id)arg1;
- (void)centralManager:(id)arg1 didDisconnectPeripheral:(id)arg2 error:(id)arg3;
- (void)centralManager:(id)arg1 didFailToConnectPeripheral:(id)arg2 error:(id)arg3;
- (void)centralManager:(id)arg1 didConnectPeripheral:(id)arg2;
- (void)centralManagerDidUpdateState:(id)arg1;
- (void)connectionTimeout:(id)arg1;
- (void)refreshConnectionAssertion;
- (void)disconnectPeripheral:(id)arg1 force:(_Bool)arg2;
- (void)connectPeripheral:(id)arg1;
- (void)refreshPeripherals;
- (id)init;
- (id)peripheralForIdentifier:(id)arg1;
- (void)connectAlways:(id)arg1;
- (void)connectOnce:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

