//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ConnectionParameters : NSObject
{
    float _minInterval;
    float _preferredInterval;
    float _maxInterval;
    int _pairs;
    int _preferredSlaveLatency;
    int _maxSlaveLatency;
    int _timeout;
}

@property(nonatomic) int timeout; // @synthesize timeout=_timeout;
@property(nonatomic) int maxSlaveLatency; // @synthesize maxSlaveLatency=_maxSlaveLatency;
@property(nonatomic) int preferredSlaveLatency; // @synthesize preferredSlaveLatency=_preferredSlaveLatency;
@property(nonatomic) int pairs; // @synthesize pairs=_pairs;
@property(nonatomic) float maxInterval; // @synthesize maxInterval=_maxInterval;
@property(nonatomic) float preferredInterval; // @synthesize preferredInterval=_preferredInterval;
@property(nonatomic) float minInterval; // @synthesize minInterval=_minInterval;

@end

