//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ServerService.h"

@class CBMutableCharacteristic, NSTimer;

@interface CTService : ServerService
{
    CBMutableCharacteristic *_currentTime;
    CBMutableCharacteristic *_localTimeInformation;
    NSTimer *_nextDSTTransitionTimer;
}

- (unsigned char)currentDstOffset;
- (BOOL)currentTimeZone;
- (void)currentTimeDidChange;
- (void)dstDidChange;
- (void)significantTimeChange;
- (void)peripheralManager:(id)arg1 central:(id)arg2 didUnsubscribeFromCharacteristic:(id)arg3;
- (void)peripheralManager:(id)arg1 central:(id)arg2 didSubscribeToCharacteristic:(id)arg3;
- (void)peripheralManager:(id)arg1 didReceiveReadRequest:(id)arg2;
- (void)stopNotifications;
- (void)startNotifications;
- (void)setupNextDSTTransitionTimer;
- (void)cancelNextDSTTransitionTimer;
- (id)readLocalTimeInformation;
- (id)localTimeInformationValue;
- (void)updateCurrentTime;
- (id)readCurrentTime;
- (id)currentTimeValue;
- (void)dealloc;
- (void)stop;
- (id)init;

@end

