//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSInputStream;

@interface DataInputStream : NSObject
{
    NSData *_value;
    NSInputStream *_stream;
    long long _byteOrder;
}

+ (id)inputStreamWithData:(id)arg1 byteOrder:(long long)arg2;
+ (id)inputStreamWithData:(id)arg1;
- (id)data;
- (_Bool)readString:(id)arg1;
- (_Bool)readUint32:(unsigned int *)arg1;
- (_Bool)readUint16:(unsigned short *)arg1;
- (_Bool)readUint8:(char *)arg1;
- (void)dealloc;
- (id)initWithValue:(id)arg1 byteOrder:(long long)arg2;

@end

