//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableData;

@interface DataOutputStream : NSObject
{
    NSMutableData *_stream;
    long long _byteOrder;
}

+ (id)outputStreamWithByteOrder:(long long)arg1;
+ (id)outputStream;
- (id)data;
- (void)writeString:(id)arg1;
- (void)writeBytes:(const void *)arg1 length:(unsigned long long)arg2;
- (void)writeData:(id)arg1;
- (void)writeUint32:(unsigned int)arg1;
- (void)writeUint16:(unsigned short)arg1;
- (void)writeUint8:(unsigned char)arg1;
- (void)dealloc;
- (id)initWithByteOrder:(long long)arg1;

@end

