//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "Endpoint.h"

@interface DeviceManagementEndpoint : Endpoint
{
}

- (void)handleDisconnectClassicDeviceCommand:(id)arg1 message:(id)arg2;
- (void)disconnectDevice:(id)arg1;
- (id)init;

@end

