//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ClientService.h"

@class CBCharacteristic, NSString;

@interface DIService : ClientService
{
    CBCharacteristic *_pnpID;
    CBCharacteristic *_fwRevision;
    CBCharacteristic *_hwRevision;
    CBCharacteristic *_serialNumber;
    unsigned char _vendorIDSource;
    unsigned short _vendorID;
    unsigned short _productID;
    unsigned short _productVersion;
}

+ (id)UUID;
@property(readonly, nonatomic) unsigned short productVersion; // @synthesize productVersion=_productVersion;
@property(readonly, nonatomic) unsigned short productID; // @synthesize productID=_productID;
@property(readonly, nonatomic) unsigned short vendorID; // @synthesize vendorID=_vendorID;
@property(readonly, nonatomic) unsigned char vendorIDSource; // @synthesize vendorIDSource=_vendorIDSource;
- (id)vendorIDSourceString;
- (void)peripheral:(id)arg1 didUpdateValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didDiscoverCharacteristicsForService:(id)arg2 error:(id)arg3;
- (void)extractIDs;
- (void)dealloc;
@property(readonly, nonatomic) NSString *serialNumber; // @dynamic serialNumber;
@property(readonly, nonatomic) NSString *hardwareRevision; // @dynamic hardwareRevision;
@property(readonly, nonatomic) NSString *firmwareRevision; // @dynamic firmwareRevision;
- (_Bool)hasIDs;
- (void)start;
- (id)initWithManager:(id)arg1 peripheral:(id)arg2 service:(id)arg3;

@end

