//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CBScalablePipeManagerDelegate.h"

@class CBScalablePipeManager, DeviceManagementEndpoint, NSString, TransactionAssertion;

@interface EndpointManager : NSObject <CBScalablePipeManagerDelegate>
{
    _Bool _persist;
    CBScalablePipeManager *_pipeManager;
    DeviceManagementEndpoint *_deviceManagementEndpoint;
    TransactionAssertion *_persistanceAssertion;
}

+ (id)instance;
@property(retain, nonatomic) TransactionAssertion *persistanceAssertion; // @synthesize persistanceAssertion=_persistanceAssertion;
@property(nonatomic) _Bool persist; // @synthesize persist=_persist;
@property(retain, nonatomic) DeviceManagementEndpoint *deviceManagementEndpoint; // @synthesize deviceManagementEndpoint=_deviceManagementEndpoint;
@property(retain, nonatomic) CBScalablePipeManager *pipeManager; // @synthesize pipeManager=_pipeManager;
- (id)scalablePipeManagerStateString;
- (id)endpointForPipe:(id)arg1;
- (void)scalablePipeManager:(id)arg1 pipeDidDisconnect:(id)arg2 error:(id)arg3;
- (void)scalablePipeManager:(id)arg1 pipeDidConnect:(id)arg2;
- (void)scalablePipeManager:(id)arg1 didUnregisterEndpoint:(id)arg2;
- (void)scalablePipeManager:(id)arg1 didRegisterEndpoint:(id)arg2 error:(id)arg3;
- (void)scalablePipeManagerDidUpdateState:(id)arg1;
- (void)refreshPersistanceAssertion;
- (id)init;
- (void)disconnectDevice:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

