//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CBPeripheral;

@interface HIDDevice : NSObject
{
    CBPeripheral *_peripheral;
    id <HIDServiceProtocol> _service;
    unsigned char _state;
}

+ (_Bool)reportsHaveMultipleReportIDs:(id)arg1;
+ (id)hidDeviceWithProperties:(id)arg1 reports:(id)arg2;
@property(readonly, nonatomic) unsigned char state; // @synthesize state=_state;
@property(retain, nonatomic) CBPeripheral *peripheral; // @synthesize peripheral=_peripheral;
@property(retain, nonatomic) id <HIDServiceProtocol> service; // @synthesize service=_service;
- (int)setReportData:(id)arg1 reportID:(unsigned char)arg2 reportType:(int)arg3;
- (int)getReportData:(id *)arg1 reportID:(unsigned char)arg2 reportType:(int)arg3;
- (void)notifyDesiredConnectionParametersDidChange;
- (void)notifyDidStop;
- (void)notifyDidStart;
- (void)dealloc;
- (id)initWithProperties:(id)arg1 reports:(id)arg2;
- (void)handleReportData:(id)arg1 reportID:(unsigned char)arg2;
- (id)desiredConnectionParameters;
- (void)stop;
- (void)start;

@end

