//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HIDDevice.h"

@class NSObject<OS_dispatch_queue>;

@interface HIDGenericDevice : HIDDevice
{
    struct __IOHIDUserDevice *_device;
    NSObject<OS_dispatch_queue> *_queue;
}

- (int)setReport:(char *)arg1 reportLength:(long long)arg2 reportID:(unsigned char)arg3 reportType:(int)arg4;
- (int)getReport:(char *)arg1 reportLength:(long long *)arg2 reportID:(unsigned char)arg3 reportType:(int)arg4;
- (void)stop;
- (void)start;
- (void)dealloc;
- (id)initWithProperties:(id)arg1 reports:(id)arg2;

@end

