//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HIDGenericDevice.h"

@interface HIDMultiReportsDevice : HIDGenericDevice
{
}

- (int)setReport:(char *)arg1 reportLength:(long long)arg2 reportID:(unsigned char)arg3 reportType:(int)arg4;
- (int)getReport:(char *)arg1 reportLength:(long long *)arg2 reportID:(unsigned char)arg3 reportType:(int)arg4;
- (void)handleReportData:(id)arg1 reportID:(unsigned char)arg2;

@end

