//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSCondition;

@interface HIDReportInfo : NSObject
{
    unsigned char _ID;
    unsigned char _type;
    _Bool _isValid;
    NSCondition *_commandCondition;
    long long _commandPending;
    _Bool _commandError;
}

@property(nonatomic) _Bool commandError; // @synthesize commandError=_commandError;
@property(readonly, nonatomic) NSCondition *commandCondition; // @synthesize commandCondition=_commandCondition;
@property(nonatomic) long long commandPending; // @synthesize commandPending=_commandPending;
@property(nonatomic) _Bool isValid; // @synthesize isValid=_isValid;
@property(readonly, nonatomic) unsigned char type; // @synthesize type=_type;
@property(readonly, nonatomic) unsigned char ID; // @synthesize ID=_ID;
- (void)dealloc;
- (id)initWithID:(unsigned char)arg1 type:(unsigned char)arg2;

@end

