//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ClientService.h"

#import "HIDServiceProtocol.h"

@class CBCharacteristic, HIDDevice, NSMapTable, NSString;

@interface HIDService : ClientService <HIDServiceProtocol>
{
    CBCharacteristic *_reportMap;
    CBCharacteristic *_hidControlPoint;
    CBCharacteristic *_hidInformation;
    CBCharacteristic *_accessoryCategory;
    NSMapTable *_reportInfoMap;
    unsigned long long _numReports;
    HIDDevice *_hidDevice;
    _Bool _pmStateIsSuspended;
    unsigned int _pmService;
    struct IONotificationPort *_pmNotificationPort;
    unsigned int _pmNotifier;
}

+ (id)UUID;
- (id)reportTypeToString:(int)arg1;
- (id)characteristicForReportID:(unsigned int)arg1 reportType:(int)arg2;
- (_Bool)allInputReportsReady;
- (void)authDidSucceedNotification:(id)arg1;
- (void)writeControlPointCommand:(unsigned char)arg1;
- (void)handlePowerManagementNotification:(unsigned int)arg1 notificationID:(long long)arg2;
- (int)setReportData:(id)arg1 reportID:(unsigned char)arg2 reportType:(int)arg3;
- (int)getReportData:(id *)arg1 reportID:(unsigned char)arg2 reportType:(int)arg3;
- (void)hidDeviceDesiredConnectionParametersDidChange;
- (void)hidDeviceDidStop;
- (void)hidDeviceDidStart;
- (void)peripheral:(id)arg1 didUpdateValueForDescriptor:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didDiscoverDescriptorsForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didUpdateNotificationStateForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didWriteValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didUpdateValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didDiscoverCharacteristicsForService:(id)arg2 error:(id)arg3;
- (void)notifyDidStartIfEverythingReady;
- (void)deregisterForPowerManagementEvents;
- (void)registerForPowerManagementEvents;
- (void)signalCommandCondition:(id)arg1 error:(_Bool)arg2;
- (void)destroyHIDDevice;
- (void)createHIDDeviceIfEverythingReady;
- (id)hidDeviceProperties;
- (void)createReportInfo:(id)arg1;
- (void)dealloc;
- (void)stop;
- (void)start;
- (id)initWithManager:(id)arg1 peripheral:(id)arg2 service:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

