//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData;

@protocol HIDServiceProtocol <NSObject>
- (int)setReportData:(NSData *)arg1 reportID:(unsigned char)arg2 reportType:(int)arg3;
- (int)getReportData:(id *)arg1 reportID:(unsigned char)arg2 reportType:(int)arg3;
- (void)hidDeviceDesiredConnectionParametersDidChange;
- (void)hidDeviceDidStop;
- (void)hidDeviceDidStart;
@end

