//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MediaRegistration : NSObject
{
    NSString *_lastKnownAttributeValue;
}

@property(retain, nonatomic) NSString *lastKnownAttributeValue; // @synthesize lastKnownAttributeValue=_lastKnownAttributeValue;
- (void)dealloc;
- (id)init;

@end

