//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ServerService.h"

#import "MediaInfoDelegate.h"

@class CBMutableCharacteristic, MediaInfo, NSMutableDictionary, NSString;

@interface MediaService : ServerService <MediaInfoDelegate>
{
    CBMutableCharacteristic *_remoteCommand;
    CBMutableCharacteristic *_entityUpdate;
    CBMutableCharacteristic *_entityAttribute;
    NSMutableDictionary *_sessions;
    MediaInfo *_info;
}

@property(retain, nonatomic) MediaInfo *info; // @synthesize info=_info;
@property(retain, nonatomic) NSMutableDictionary *sessions; // @synthesize sessions=_sessions;
- (id)entityUpdateFlagsToString:(unsigned char)arg1;
- (id)attributeIDToString:(unsigned char)arg1 entityID:(unsigned char)arg2;
- (id)remoteCommandIDToString:(unsigned char)arg1;
- (id)invocationForNotifyAttributeIDs:(id)arg1 entityID:(unsigned char)arg2 central:(id)arg3;
- (id)currentAttributeValueForAttributeID:(unsigned char)arg1 entityID:(unsigned char)arg2;
- (id)sessionForCentral:(id)arg1;
- (unsigned long long)subscriptionCount;
- (void)mediaVolumeDidChange;
- (void)mediaInfoDidChange;
- (void)mediaStateDidChange;
- (void)mediaPlayerDidChange;
- (void)supportedCommandsDidChange;
- (void)peripheralManager:(id)arg1 central:(id)arg2 didUnsubscribeFromCharacteristic:(id)arg3;
- (void)peripheralManager:(id)arg1 central:(id)arg2 didSubscribeToCharacteristic:(id)arg3;
- (void)peripheralManager:(id)arg1 didReceiveWriteRequests:(id)arg2;
- (void)peripheralManager:(id)arg1 didReceiveReadRequest:(id)arg2;
- (void)stopNotifications;
- (void)startNotifications;
- (void)attributeIDsDidChange:(id)arg1 entityID:(unsigned char)arg2;
- (void)supportedCommandsDidChange:(id)arg1;
- (void)notifyAttributeIDs:(id)arg1 entityID:(unsigned char)arg2 central:(id)arg3;
- (void)notifySupportedCommands:(id)arg1 central:(id)arg2;
- (void)notifyAttributeValue:(id)arg1 attributeID:(unsigned char)arg2 entityID:(unsigned char)arg3 central:(id)arg4;
- (void)notifySupportedCommandsValue:(id)arg1 central:(id)arg2;
- (long long)handleEntityAttributeWrite:(id)arg1;
- (long long)handleEntityAttributeRead:(id)arg1;
- (long long)handleEntityUpdateWrite:(id)arg1 action:(id *)arg2;
- (long long)handleRemoteCommandWrite:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

