//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ServerService.h"

@class NSMutableDictionary, NSSet;

@interface MediaSession : ServerService
{
    NSSet *_lastKnownSupportedCommands;
    NSMutableDictionary *_registrations;
    unsigned char _loadedEntityID;
    unsigned char _loadedAttributeID;
}

@property(nonatomic) unsigned char loadedAttributeID; // @synthesize loadedAttributeID=_loadedAttributeID;
@property(nonatomic) unsigned char loadedEntityID; // @synthesize loadedEntityID=_loadedEntityID;
@property(retain, nonatomic) NSSet *lastKnownSupportedCommands; // @synthesize lastKnownSupportedCommands=_lastKnownSupportedCommands;
- (id)registrationForAttributeID:(unsigned char)arg1 entityID:(unsigned char)arg2;
- (id)lastKnownAttributeValueForAttributeID:(unsigned char)arg1 entityID:(unsigned char)arg2;
- (void)setLastKnownAttributeValue:(id)arg1 attributeID:(unsigned char)arg2 entityID:(unsigned char)arg3;
- (_Bool)isRegisteredForAttributeID:(unsigned char)arg1 entityID:(unsigned char)arg2;
- (id)notifiableAttributeIDs:(id)arg1 entityID:(unsigned char)arg2;
- (void)setRegisteredAttributeIDs:(id)arg1 entityID:(unsigned char)arg2;
- (void)dealloc;
- (id)init;

@end

