//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (BTLEServer)
- (id)UTF8DataWithMaxLength:(unsigned long long)arg1 ellipsis:(_Bool)arg2 isTruncated:(_Bool *)arg3;
- (id)substringWithValidUnicode;
@end

