//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData;

@interface OutboundMessage : NSObject
{
    NSData *_data;
    unsigned long long _offset;
}

@property(nonatomic) unsigned long long offset; // @synthesize offset=_offset;
@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
- (void)dealloc;
- (id)initWithData:(id)arg1;

@end

