//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSStreamDelegate.h"

@class CBScalablePipe, NSMutableArray, NSMutableData, NSSet, NSString;

@interface Pipe : NSObject <NSStreamDelegate>
{
    id <PipeDelegate> _delegate;
    CBScalablePipe *_pipe;
    NSSet *_supportedCommands;
    NSMutableArray *_txMessageQueue;
    NSMutableData *_receivedMessage;
    NSMutableData *_incomingBuffer;
}

@property(retain, nonatomic) NSMutableData *incomingBuffer; // @synthesize incomingBuffer=_incomingBuffer;
@property(retain, nonatomic) NSMutableData *receivedMessage; // @synthesize receivedMessage=_receivedMessage;
@property(retain, nonatomic) NSMutableArray *txMessageQueue; // @synthesize txMessageQueue=_txMessageQueue;
@property(retain, nonatomic) NSSet *supportedCommands; // @synthesize supportedCommands=_supportedCommands;
@property(readonly, retain, nonatomic) CBScalablePipe *pipe; // @synthesize pipe=_pipe;
@property(readonly, nonatomic) id <PipeDelegate> delegate; // @synthesize delegate=_delegate;
- (void)stream:(id)arg1 handleEvent:(unsigned long long)arg2;
- (void)receiveMessage:(char *)arg1 length:(long long)arg2;
- (void)sendNextQueuedMessage;
- (void)sendMessage:(id)arg1;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1 pipe:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

