//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CBPeripheralManagerDelegate.h"

@class CBPeripheralManager, NSMapTable, NSMutableArray, NSString, TransactionAssertion;

@interface ServerServiceManager : NSObject <CBPeripheralManagerDelegate>
{
    CBPeripheralManager *_peripheralManager;
    NSMapTable *_serverServiceMap;
    _Bool _persist;
    TransactionAssertion *_persistanceAssertion;
    NSMutableArray *_pendingATTUpdates;
}

+ (void)initialize;
+ (id)instance;
- (id)peripheralManagerStateString;
- (id)nameForCentral:(id)arg1;
- (void)peripheralManagerIsReadyToUpdateSubscribers:(id)arg1;
- (void)peripheralManager:(id)arg1 central:(id)arg2 didUnsubscribeFromCharacteristic:(id)arg3;
- (void)peripheralManager:(id)arg1 central:(id)arg2 didSubscribeToCharacteristic:(id)arg3;
- (void)peripheralManager:(id)arg1 didReceiveWriteRequests:(id)arg2;
- (void)peripheralManager:(id)arg1 didReceiveReadRequest:(id)arg2;
- (void)peripheralManager:(id)arg1 didAddService:(id)arg2 error:(id)arg3;
- (void)peripheralManagerDidUpdateState:(id)arg1;
- (void)updateValue:(id)arg1 forCharacteristic:(id)arg2 onSubscribedCentrals:(id)arg3;
- (void)respondToRequest:(id)arg1 withResult:(long long)arg2;
- (void)removeService:(id)arg1;
- (void)addService:(id)arg1;
- (void)refreshPersistanceAssertion;
- (void)destroyServices;
- (void)createServices;
- (id)init;
- (void)setPersist:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

