//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CBPeripheralManagerDelegate.h"

@class CBMutableService, NSString;

@interface ServerService : NSObject <CBPeripheralManagerDelegate>
{
    CBMutableService *_service;
}

@property(readonly, nonatomic) CBMutableService *service; // @synthesize service=_service;
- (void)peripheralManager:(id)arg1 didAddService:(id)arg2 error:(id)arg3;
- (void)peripheralManagerDidUpdateState:(id)arg1;
- (void)dealloc;
- (void)updateValue:(id)arg1 forCharacteristic:(id)arg2 onSubscribedCentrals:(id)arg3;
- (void)respondToRequest:(id)arg1 withResult:(long long)arg2;
- (id)init;
- (void)stop;
- (void)start;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

